import type { SchoolSession, SchoolUnlock } from "./types";

/**
 * The thirty sessions.
 *
 * READ THE STEP LIST, NOT THE TITLES. The arc only works if each session is
 * one idea, taught then used then named: TEACH -> a board where the idea is
 * the only thing that matters -> a drill that proves it -> RECAP in the
 * child's own words. Sessions that skip straight to a drill produce children
 * who can solve puzzles and cannot play chess, which is the failure mode this
 * course exists to avoid.
 *
 * EVERY POSITION HERE IS VERIFIED. scripts/test-chess-school-v2.js loads each
 * FEN into chess.js and plays every accepted move against it. A position that
 * cannot be reached, or a solution that is not legal from it, fails the suite
 * rather than stranding a child on a puzzle with no answer. That check exists
 * because this repository has previously shipped illegal puzzle positions.
 *
 * OLLIE IS SCOPED. Each session carries three lines — intro, mistake, success
 * — and they are about THIS session's skill. There is no general chat here by
 * design: an open text box is a support burden, a safety surface, and a way
 * for a child to end up discussing something other than forks during the fork
 * lesson.
 */

const FORK_MASTER: SchoolUnlock = {
  id: "fork_master",
  title: "Fork Master",
  tagline: "Challenge me.",
  emoji: "🍴",
};

const FIRST_GAME: SchoolUnlock = {
  id: "first_game",
  title: "First Game Played",
  tagline: "I played a whole game of chess.",
  emoji: "♟️",
};

const FIRST_CHECKMATE: SchoolUnlock = {
  id: "first_checkmate",
  title: "First Checkmate",
  tagline: "I found checkmate.",
  emoji: "👑",
};

const REAL_OPPONENT: SchoolUnlock = {
  id: "real_opponent",
  title: "Played a Real Person",
  tagline: "I did that to a real person.",
  emoji: "🤝",
};

const INDEPENDENT: SchoolUnlock = {
  id: "independent",
  title: "No Hints Needed",
  tagline: "I won it on my own.",
  emoji: "🧠",
};

const GRADUATE: SchoolUnlock = {
  id: "graduate",
  title: "Chess School Graduate",
  tagline: "Challenge me to a game!",
  emoji: "🎓",
};

/** Every share card the course can award, for the home screen and the tests. */
export const SCHOOL_UNLOCKS: readonly SchoolUnlock[] = [
  FORK_MASTER,
  FIRST_GAME,
  FIRST_CHECKMATE,
  REAL_OPPONENT,
  INDEPENDENT,
  GRADUATE,
];

export const SCHOOL_SESSIONS: readonly SchoolSession[] = [
  // ────────────────────────── ACT 1 — I SPEAK CHESS ──────────────────────────
  {
    id: "s01-welcome",
    number: 1,
    moduleId: "m1-board",
    title: "Welcome to Chess School",
    subtitle: "The board, and where everything stands.",
    skillTags: ["board_setup"],
    starred: true,
    estimatedMinutes: 10,
    status: "playable",
    ollie: {
      intro: "Today we learn the board. You've got this.",
      mistake: "That's okay. Even I did that when I was learning.",
      success: "You didn't get lucky. You saw it.",
    },
    steps: [
      {
        id: "s01-teach",
        type: "teach",
        title: "Sixty-four squares",
        lines: [
          "A chess board is eight squares across and eight squares down.",
          "White always starts at the bottom. The board turns so that YOUR pieces are closest to you.",
          "Here is what it looks like when everything is home.",
        ],
        fen: "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
      },
      {
        id: "s01-guided",
        type: "guided_board",
        title: "Make the very first move",
        fen: "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
        goal: "Move one of your front-row pawns two squares forward.",
        acceptMoves: ["e4", "d4", "c4", "f4"],
        hintLadder: [
          "Your pawns are the whole front row. Tap one.",
          "The two in the middle are the best ones to move first.",
          "Tap the pawn on e2, then tap the square e4.",
        ],
        onWrong: "That's a real move! But today we're moving a middle pawn two squares. Try the one in front of your king.",
      },
      {
        id: "s01-guided-2",
        type: "guided_board",
        title: "Black answers — now you again",
        fen: "rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2",
        goal: "Black copied you. Chess goes back and forth like that. Your turn — move the pawn in front of your Queen.",
        acceptMoves: ["d4", "d3"],
        hintLadder: [
          "Your Queen is the tall piece next to your King. Find the pawn in front of her.",
          "That pawn is on d2. It can go one square or two.",
          "Tap d2, then tap d4.",
        ],
        onWrong: "That's allowed — but let's get the Queen's pawn moving. It's the one on d2.",
      },
      {
        id: "s01-ceremony",
        type: "ceremony",
        title: "Your first move",
        headline: "YOU MADE YOUR FIRST CHESS MOVE",
        lines: ["Every game ever played started exactly like that.", "Yours just did too."],
      },
      {
        id: "s01-recap",
        type: "recap",
        title: "You started a chess game",
        learned: ["You know how the board is set up.", "You made the first move of a chess game."],
        nextTeaser: "Next: the smallest piece with the biggest secret.",
      },
    ],
  },
  {
    id: "s02-pawn",
    number: 2,
    moduleId: "m1-board",
    title: "Meet the Pawn",
    subtitle: "The soldier that can become a Queen.",
    skillTags: ["pawn_movement", "pawn_promotion"],
    starred: true,
    estimatedMinutes: 12,
    status: "playable",
    superpowerId: "pawn-promotion",
    ollie: {
      intro: "Today we learn the Pawn. Everyone thinks it's the weakest piece. Everyone is wrong.",
      mistake: "That's okay. Pawns are fussy — they only go forwards.",
      success: "That's it. You moved a soldier.",
    },
    steps: [
      {
        id: "s02-teach",
        type: "teach",
        title: "The soldier",
        lines: [
          "Pawns only walk FORWARD. Never backwards. Never sideways.",
          "On its very first move a pawn may go one square or two. After that, one at a time.",
          "And here is the secret: a pawn that walks all the way to the far end becomes a QUEEN.",
        ],
      },
      {
        id: "s02-guided",
        type: "guided_board",
        title: "Walk the last step",
        fen: "4k3/P7/8/8/8/8/8/4K3 w - - 0 1",
        goal: "This pawn is one step from the end. Turn it into a Queen.",
        acceptMoves: ["a8=Q", "a8=Q+", "a7a8q"],
        hintLadder: [
          "The pawn is on a7. The end of the board is one square away.",
          "Tap the pawn, then tap the square right at the top.",
          "Tap a7, then a8 — and choose the Queen.",
        ],
        onWrong: "Nearly! Move the PAWN to the very last row and it transforms.",
      },
      {
        id: "s02-drill",
        type: "puzzle_drill",
        title: "Soldier practice",
        drill: {
          passRequired: 2,
          puzzles: [
            { id: "s02-p1", fen: "4k3/8/8/8/8/8/4P3/4K3 w - - 0 1", prompt: "Move the pawn forward TWO squares — it's his first move.", solutionMoves: ["e4"], hint: "First move only: two squares is allowed." },
            { id: "s02-p2", fen: "4k3/8/8/8/4P3/8/8/4K3 w - - 0 1", prompt: "He's moved before. Now how far can he go?", solutionMoves: ["e5"], hint: "After the first move it's one square at a time." },
            { id: "s02-p3", fen: "4k3/1P6/8/8/8/8/8/4K3 w - - 0 1", prompt: "One step from the end. Make him a Queen.", solutionMoves: ["b8=Q", "b8=Q+", "b7b8q"], hint: "Tap b7, then b8." },
          ],
          remedial: { id: "s02-r1", fen: "4k3/8/8/8/8/8/4P3/4K3 w - - 0 1", prompt: "One more. Just move the pawn forward.", solutionMoves: ["e3", "e4"], hint: "Straight up. One or two squares." },
          remedialTeach: "Pawns: forward only. Two squares the first time if you like, one square after that. Reach the end and it turns into a Queen.",
        },
      },
      {
        id: "s02-ceremony",
        type: "ceremony",
        title: "Superpower unlocked",
        headline: "PAWN PROMOTION",
        lines: ["The soldier that can become a Queen.", "Nobody expects it. That is why it wins games."],
      },
      {
        id: "s02-recap",
        type: "recap",
        title: "You promoted a pawn",
        learned: ["Pawns move forwards only.", "A pawn that reaches the end becomes a Queen."],
        nextTeaser: "Next: how pawns take things.",
      },
    ],
  },
  {
    id: "s03-pawn-captures",
    number: 3,
    moduleId: "m1-board",
    title: "Pawn Captures",
    subtitle: "Forward to walk. Diagonal to take.",
    skillTags: ["pawn_capture"],
    starred: false,
    estimatedMinutes: 10,
    status: "playable",
    ollie: {
      intro: "Today we learn how pawns capture. It is not how they walk.",
      mistake: "That's okay. Pawns take diagonally — corner to corner.",
      success: "Exactly. Straight to walk, slanted to take.",
    },
    steps: [
      {
        id: "s03-teach",
        type: "teach",
        title: "Straight to walk, slanted to take",
        lines: [
          "A pawn WALKS straight forward — but it cannot capture that way.",
          "To take a piece, a pawn steps one square FORWARD AND DIAGONAL.",
          "So a pawn can be blocked by a piece right in front of it and do nothing about it.",
        ],
      },
      {
        id: "s03-drill",
        type: "puzzle_drill",
        title: "Take with the pawn",
        drill: {
          passRequired: 2,
          puzzles: [
            {
              id: "s03-p1",
              fen: "4k3/8/8/3p4/4P3/8/8/4K3 w - - 0 1",
              prompt: "Capture the black pawn.",
              solutionMoves: ["exd5"],
              hint: "Your pawn is on e4. The black pawn is up and to the left.",
            },
            {
              id: "s03-p2",
              fen: "4k3/8/8/5n2/4P3/8/8/4K3 w - - 0 1",
              prompt: "Capture the knight.",
              solutionMoves: ["exf5"],
              hint: "Up and to the RIGHT this time.",
            },
            {
              id: "s03-p3",
              fen: "4k3/8/8/3r4/4P3/8/8/4K3 w - - 0 1",
              prompt: "Capture the rook.",
              solutionMoves: ["exd5"],
              hint: "A rook is worth much more than a pawn. Take it.",
            },
          ],
          remedial: {
            id: "s03-r1",
            fen: "4k3/8/8/3p4/4P3/8/8/4K3 w - - 0 1",
            prompt: "One more. Take the black pawn with your pawn.",
            solutionMoves: ["exd5"],
            hint: "Tap your pawn on e4, then tap the black pawn.",
          },
          remedialTeach: "Here it is again, smaller. A pawn takes by stepping one square forward AND sideways at the same time — like a little corner step.",
        },
      },
      {
        id: "s03-recap",
        type: "recap",
        title: "You can capture with pawns",
        learned: ["Pawns walk straight.", "Pawns capture diagonally."],
        nextTeaser: "Next: the piece that jumps over walls.",
      },
    ],
  },
  {
    id: "s04-knight",
    number: 4,
    moduleId: "m2-pawns",
    title: "Meet the Knight",
    subtitle: "The only piece that jumps over walls.",
    skillTags: ["knight_movement"],
    starred: true,
    estimatedMinutes: 12,
    status: "playable",
    superpowerId: "knight-jump",
    ollie: {
      intro: "Today we learn the Knight. It does something no other piece can do.",
      mistake: "That's okay. The Knight's move feels strange at first — it's an L.",
      success: "You jumped it. Nothing else on this board can do that.",
    },
    steps: [
      {
        id: "s04-teach",
        type: "teach",
        title: "The L-shape",
        lines: [
          "The Knight moves in an L: two squares one way, then one square to the side.",
          "Here is the superpower — the Knight JUMPS. Pieces in the way do not stop it.",
          "It is the only piece in chess that can do that.",
        ],
      },
      {
        id: "s04-guided",
        type: "guided_board",
        title: "Jump over your own wall",
        fen: "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
        goal: "Every piece is boxed in behind a wall of pawns. Move a Knight anyway.",
        acceptMoves: ["Nf3", "Nc3", "Nh3", "Na3"],
        hintLadder: [
          "Look at the back row. The horses are the Knights.",
          "The Knight does not care about the pawns in front of it.",
          "Tap the Knight on g1, then tap f3.",
        ],
        onWrong: "That's legal — but today it's the Knight's turn. Find a horse.",
      },
      {
        id: "s04-drill",
        type: "puzzle_drill",
        title: "Knight takes",
        drill: {
          passRequired: 2,
          puzzles: [
            {
              id: "s04-p1",
              fen: "4k3/8/8/3p4/8/4N3/8/4K3 w - - 0 1",
              prompt: "Capture the pawn with your Knight.",
              solutionMoves: ["Nxd5"],
              hint: "Two up, one across.",
            },
            {
              id: "s04-p2",
              fen: "4k3/8/5r2/8/4N3/8/8/4K3 w - - 0 1",
              prompt: "Capture the rook with your Knight.",
              solutionMoves: ["Nxf6"],
              hint: "Two up, one to the right.",
            },
            {
              id: "s04-p3",
              fen: "4k3/8/8/2b5/4N3/8/8/4K3 w - - 0 1",
              prompt: "Capture the bishop with your Knight.",
              solutionMoves: ["Nxc5"],
              hint: "One up, two across.",
            },
          ],
          remedial: {
            id: "s04-r1",
            fen: "4k3/8/8/3p4/8/4N3/8/4K3 w - - 0 1",
            prompt: "One more. Knight takes the pawn.",
            solutionMoves: ["Nxd5"],
            hint: "Count it out loud: up, up, left.",
          },
          remedialTeach: "Say it as you move: UP, UP, ACROSS. That is the whole L. Try that on this one.",
        },
      },
      {
        id: "s04-ceremony",
        type: "ceremony",
        title: "Superpower unlocked",
        headline: "KNIGHT JUMP",
        lines: ["The only piece that jumps over walls.", "Now you have a piece nobody can block."],
      },
      {
        id: "s04-recap",
        type: "recap",
        title: "You can move the Knight",
        learned: ["The Knight moves in an L.", "The Knight jumps over anything in the way."],
        nextTeaser: "Next: the laser.",
      },
    ],
  },
  {
    id: "s05-bishop",
    number: 5,
    moduleId: "m2-pawns",
    title: "Meet the Bishop",
    subtitle: "The laser on diagonals.",
    skillTags: ["bishop_movement"],
    starred: false,
    estimatedMinutes: 10,
    status: "playable",
    superpowerId: "bishop-laser",
    ollie: {
      intro: "Today we learn the Bishop. Think of it as a laser beam.",
      mistake: "That's okay. Bishops only travel on slanted lines.",
      success: "That's the laser. Straight down the diagonal.",
    },
    steps: [
      {
        id: "s05-teach",
        type: "teach",
        title: "Slanted lines only",
        lines: [
          "The Bishop slides along DIAGONALS — the slanted lines, corner to corner.",
          "It can go as far as it likes, until something is in the way.",
          "A Bishop that starts on a light square stays on light squares its whole life.",
        ],
      },
      {
        id: "s05-guided",
        type: "guided_board",
        title: "Fire the laser",
        fen: "4k3/8/7p/8/8/8/8/2B1K3 w - - 0 1",
        goal: "Take the pawn in the far corner — in one move.",
        acceptMoves: ["Bxh6"],
        hintLadder: [
          "The Bishop is on c1. Follow the slanted line up and to the right.",
          "Nothing is in the way. The laser goes all the way.",
          "Tap the Bishop, then tap the pawn on h6.",
        ],
        onWrong: "The Bishop can go further than that. Follow the diagonal all the way to the pawn.",
      },
      {
        id: "s05-drill",
        type: "puzzle_drill",
        title: "Laser practice",
        drill: {
          passRequired: 2,
          puzzles: [
            { id: "s05-p1", fen: "4k3/8/8/8/5p2/8/8/2B1K3 w - - 0 1", prompt: "Take the pawn with the Bishop.", solutionMoves: ["Bxf4"], hint: "Up and to the right, three squares." },
            { id: "s05-p2", fen: "4k3/8/8/8/8/r7/8/2B1K3 w - - 0 1", prompt: "Take the rook with the Bishop.", solutionMoves: ["Bxa3"], hint: "The other diagonal — up and to the LEFT." },
            { id: "s05-p3", fen: "4k3/8/8/8/8/8/7q/2B1K3 w - - 0 1", prompt: "Careful — which piece can the Bishop actually reach? Take it.", solutionMoves: ["Bd2", "Be3", "Bf4", "Bg5", "Bh6", "Bb2", "Ba3"], hint: "Trick question: the Queen is on a straight line, and Bishops don't do straight lines. Any Bishop move counts." },
          ],
          remedial: { id: "s05-r1", fen: "4k3/8/8/8/8/4p3/8/2B1K3 w - - 0 1", prompt: "One more. Take the pawn on the diagonal.", solutionMoves: ["Bxe3"], hint: "Two squares up and to the right." },
          remedialTeach: "Put your finger on the Bishop and slide it corner-to-corner. If your finger lands on the piece, the Bishop can take it. If it doesn't, it can't — no matter how close.",
        },
      },
      {
        id: "s05-recap",
        type: "recap",
        title: "You can move the Bishop",
        learned: ["Bishops slide along diagonals.", "A Bishop never changes colour of square."],
        nextTeaser: "Next: the train.",
      },
    ],
  },
  {
    id: "s06-rook",
    number: 6,
    moduleId: "m3-knights-bishops",
    title: "Meet the Rook",
    subtitle: "The train on straight lines.",
    skillTags: ["rook_movement"],
    starred: false,
    estimatedMinutes: 10,
    status: "playable",
    superpowerId: "rook-train",
    ollie: {
      intro: "Today we learn the Rook. It runs on rails.",
      mistake: "That's okay. Rooks go straight — never slanted.",
      success: "All the way down the line. That's a Rook.",
    },
    steps: [
      {
        id: "s06-teach",
        type: "teach",
        title: "Rails, not diagonals",
        lines: [
          "The Rook slides in STRAIGHT lines: up, down, left, right.",
          "As far as it wants — until something blocks the track.",
          "Rooks are strong. Only the Queen is worth more.",
        ],
      },
      {
        id: "s06-guided",
        type: "guided_board",
        title: "Run the track",
        fen: "4k3/r7/8/8/8/8/8/R3K3 w - - 0 1",
        goal: "Capture the black rook without moving anything else.",
        acceptMoves: ["Rxa7"],
        hintLadder: [
          "Both rooks are on the same line — the left edge.",
          "The track is clear the whole way.",
          "Tap your rook on a1, then tap the black rook on a7.",
        ],
        onWrong: "Follow the straight line. Your rook can travel the whole way in one move.",
      },
      {
        id: "s06-drill",
        type: "puzzle_drill",
        title: "On the rails",
        drill: {
          passRequired: 2,
          puzzles: [
            { id: "s06-p1", fen: "4k3/8/8/8/8/8/8/R2nK3 w - - 0 1", prompt: "Take the knight with the rook.", solutionMoves: ["Rxd1"], hint: "Same row. Slide along it." },
            { id: "s06-p2", fen: "4k3/8/8/8/R4b2/8/8/4K3 w - - 0 1", prompt: "Take the bishop with the rook.", solutionMoves: ["Rxf4"], hint: "Straight across the board." },
            { id: "s06-p3", fen: "4k3/8/8/8/8/8/8/R3K2b w - - 0 1", prompt: "Careful — can the rook reach the bishop? Make the best rook move.", solutionMoves: ["Ra8+", "Ra7", "Ra6", "Ra5", "Ra4", "Ra3", "Ra2", "Rb1", "Rc1", "Rd1"], hint: "Your own King is in the way on the row. Any rook move counts — the trap was noticing that." },
          ],
          remedial: { id: "s06-r1", fen: "4k3/8/8/8/p7/8/8/R3K3 w - - 0 1", prompt: "One more. Take the pawn up the column.", solutionMoves: ["Rxa4"], hint: "Straight up. Nothing in the way." },
          remedialTeach: "A rook is a train on rails: straight up, straight across, never diagonal. Trace the rail with your finger until it hits something. That's what the rook can take.",
        },
      },
      {
        id: "s06-recap",
        type: "recap",
        title: "You can move the Rook",
        learned: ["Rooks slide in straight lines.", "Rooks are worth more than knights and bishops."],
        nextTeaser: "Next: the boss, and the one you protect.",
      },
    ],
  },
  {
    id: "s07-queen-king",
    number: 7,
    moduleId: "m3-knights-bishops",
    title: "Meet the Queen and King",
    subtitle: "The boss, and the one you protect.",
    skillTags: ["queen_movement", "king_movement"],
    starred: false,
    estimatedMinutes: 12,
    status: "playable",
    superpowerId: "queen-boss",
    ollie: {
      intro: "Today we meet the two most important pieces on the board.",
      mistake: "That's okay. The Queen can do a lot — try a different direction.",
      success: "That's the boss at work.",
    },
    steps: [
      {
        id: "s07-teach",
        type: "teach",
        title: "The boss and the one you protect",
        lines: [
          "The QUEEN does everything the Rook does AND everything the Bishop does. Straight and slanted, any distance.",
          "The KING moves one square at a time, in any direction.",
          "The King is not strong. He is precious. Lose him and the game is over.",
        ],
      },
      {
        id: "s07-guided",
        type: "guided_board",
        title: "The Queen takes",
        fen: "4k3/8/8/8/8/8/3p4/3QK3 w - - 0 1",
        goal: "Take the black pawn with your Queen.",
        acceptMoves: ["Qxd2"],
        hintLadder: [
          "The Queen is next to your King.",
          "The pawn is directly in front of the Queen.",
          "Tap the Queen on d1, then the pawn on d2.",
        ],
        onWrong: "Almost. Use the QUEEN, not the King.",
      },
      {
        id: "s07-drill",
        type: "puzzle_drill",
        title: "The boss at work",
        drill: {
          passRequired: 2,
          puzzles: [
            { id: "s07-p1", fen: "4k3/8/8/8/6r1/8/8/3QK3 w - - 0 1", prompt: "Take the rook with the Queen — she can go diagonally like a Bishop.", solutionMoves: ["Qxg4"], hint: "Up and to the right, all the way." },
            { id: "s07-p2", fen: "4k3/8/8/3n4/8/8/8/3QK3 w - - 0 1", prompt: "Take the knight with the Queen — she can go straight like a Rook.", solutionMoves: ["Qxd5"], hint: "Straight up the column." },
            { id: "s07-p3", fen: "4k3/8/8/8/8/8/5p2/4K3 w - - 0 1", prompt: "The King can capture too — one square. Take the pawn.", solutionMoves: ["Kxf2"], hint: "The pawn is right next to your King." },
          ],
          remedial: { id: "s07-r1", fen: "4k3/8/8/8/8/8/3p4/3QK3 w - - 0 1", prompt: "One more. Queen takes the pawn in front of her.", solutionMoves: ["Qxd2"], hint: "One square straight up." },
          remedialTeach: "Queen = Rook + Bishop. Straight OR slanted, as far as she likes. The King is the same directions but only ONE step. Try the Queen again.",
        },
      },
      {
        id: "s07-ceremony",
        type: "ceremony",
        title: "Two superpowers",
        headline: "QUEEN AND KING",
        lines: [
          "The Queen: the boss. Rook and Bishop in one piece.",
          "The King: the one you protect.",
        ],
      },
      {
        id: "s07-recap",
        type: "recap",
        title: "You know every piece",
        learned: ["The Queen moves straight AND diagonally.", "The King moves one square at a time."],
        nextTeaser: "Next: your first proper game.",
      },
    ],
  },
  {
    id: "s08-boss-mini-game",
    number: 8,
    moduleId: "m3-knights-bishops",
    title: "Boss Battle: Your First Mini Game",
    subtitle: "Everything you know, on one board.",
    skillTags: ["full_game"],
    starred: true,
    estimatedMinutes: 18,
    status: "playable",
    ollie: {
      intro: "You know every piece now. Time to use them all at once.",
      mistake: "That's okay. Keep going — a game is lots of moves, not one.",
      success: "You just played chess. Actual chess.",
    },
    steps: [
      {
        id: "s08-teach",
        type: "teach",
        title: "How a game works",
        lines: [
          "White moves, then Black moves. Always one at a time.",
          "You do not have to plan ten moves ahead. Just make good moves.",
          "I'll be right here.",
        ],
      },
      {
        id: "s08-bot",
        type: "bot_match",
        title: "Your first mini game",
        goal: "Play eight of your own moves against a very gentle opponent.",
        movesRequired: 8,
        hintsAllowed: true,
      },
      {
        id: "s08-ceremony",
        type: "ceremony",
        title: "First game played",
        headline: "YOU PLAYED A GAME OF CHESS",
        lines: ["Not a puzzle. A game.", "That is further than most people ever get."],
        unlock: FIRST_GAME,
        epic: true,
      },
      {
        id: "s08-recap",
        type: "recap",
        title: "You played a real game",
        learned: ["You played a full mini game.", "You used every piece you have learned."],
        nextTeaser: "Next: what it means when someone shouts CHECK.",
      },
    ],
    shareUnlock: FIRST_GAME,
  },

  // ────────────────────────── ACT 2 — I SEE TRAPS ──────────────────────────
  {
    id: "s09-check",
    number: 9,
    moduleId: "m4-rooks-queen",
    title: "What is Check?",
    subtitle: "The King is under attack.",
    skillTags: ["check"],
    starred: false,
    estimatedMinutes: 10,
    status: "playable",
    ollie: {
      intro: "Today we learn check. It is chess for 'careful — your King!'",
      mistake: "That's okay. Check means attacking the King itself.",
      success: "That's check. You attacked the King.",
    },
    steps: [
      {
        id: "s09-teach",
        type: "teach",
        title: "Careful — your King",
        lines: [
          "CHECK means the King is being attacked right now.",
          "When you are in check you MUST deal with it. You cannot ignore it and do something else.",
          "You can move the King, block the attack, or capture the attacker.",
        ],
      },
      {
        id: "s09-guided",
        type: "guided_board",
        title: "Give check",
        fen: "4k3/8/8/8/8/8/8/R6K w - - 0 1",
        goal: "Attack the black King with your rook.",
        acceptMoves: ["Ra8+", "Re1+"],
        hintLadder: [
          "The black King is on the top row.",
          "Your rook travels in straight lines. Can it reach the King's row or the King's column?",
          "Tap the rook, then tap a8.",
        ],
        onWrong: "Close. You need a move that ATTACKS the King — put your rook on the same line as him.",
      },
      {
        id: "s09-drill",
        type: "puzzle_drill",
        title: "Say check",
        drill: {
          passRequired: 2,
          puzzles: [
            { id: "s09-p1", fen: "4k3/8/8/8/8/8/8/3QK3 w - - 0 1", prompt: "Give check with the Queen.", solutionMoves: ["Qe2+", "Qd8+", "Qd7+", "Qh5+", "Qa4+"], hint: "Any square where the Queen looks straight at the King." },
            { id: "s09-p2", fen: "4k3/8/8/1N6/8/8/8/4K3 w - - 0 1", prompt: "Give check with the Knight.", solutionMoves: ["Nc7+", "Nd6+"], hint: "An L-jump that lands attacking the King." },
            { id: "s09-p3", fen: "4k3/8/8/8/8/8/8/4KB2 w - - 0 1", prompt: "Give check with the Bishop.", solutionMoves: ["Bb5+"], hint: "Find the diagonal that ends on the King." },
          ],
          remedial: { id: "s09-r1", fen: "4k3/8/8/8/8/8/8/R6K w - - 0 1", prompt: "One more. Check the King with the rook.", solutionMoves: ["Ra8+", "Re1+"], hint: "Get onto the King's row or column." },
          remedialTeach: "Check just means: my piece is pointing at your King RIGHT NOW. Pick a piece, and find the square where it would be pointing at him.",
        },
      },
      {
        id: "s09-recap",
        type: "recap",
        title: "You understand check",
        learned: ["Check means the King is attacked.", "You must always answer a check."],
        nextTeaser: "Next: your first guided game.",
      },
    ],
  },
  {
    id: "s10-first-guided-game",
    number: 10,
    moduleId: "m4-rooks-queen",
    title: "Your First Guided Game",
    subtitle: "A whole game, with me next to you.",
    skillTags: ["full_game"],
    starred: true,
    estimatedMinutes: 22,
    status: "playable",
    ollie: {
      intro: "Today you play a whole game and I stay right beside you the entire time.",
      mistake: "That's okay. Nobody plays a clean game at first. Keep going.",
      success: "You played a game of chess. I barely had to say anything.",
    },
    steps: [
      {
        id: "s10-teach",
        type: "teach",
        title: "Three rules for a whole game",
        lines: [
          "One: move pawns in the middle first, so your pieces can get out.",
          "Two: bring out your Knights and Bishops before your Queen.",
          "Three: if a piece of yours can be taken for free, move it or defend it.",
        ],
      },
      {
        id: "s10-bot",
        type: "bot_match",
        title: "A guided game",
        goal: "Play twelve of your own moves. Hints are always available — use them whenever you like.",
        movesRequired: 12,
        hintsAllowed: true,
        prelude: {
          headline: "Everything you've learned comes together now.",
          lines: [
            "The Pawn. The Knight. The Bishop. The Rook. The Queen. The King.",
            "Every one of them is about to be on the same board, and every move is going to be yours.",
            "Ready?",
          ],
          cta: "Play my first game",
        },
      },
      {
        id: "s10-ceremony",
        type: "ceremony",
        title: "A whole game",
        headline: "YOU PLAYED A WHOLE GAME OF CHESS",
        lines: [
          "Opening, middle, and on to the end — with your own moves.",
          "You didn't just learn chess moves. You played a game.",
        ],
        epic: true,
      },
      {
        id: "s10-recap",
        type: "recap",
        title: "You played a guided game",
        learned: ["You played a longer game start to finish.", "You know the three opening rules."],
        nextTeaser: "Next: spotting pieces that are free to take.",
      },
    ],
  },
  {
    id: "s11-hanging-pieces",
    number: 11,
    moduleId: "m4-rooks-queen",
    title: "Hanging Pieces",
    subtitle: "Free stuff, if you look.",
    skillTags: ["hanging_pieces"],
    starred: false,
    estimatedMinutes: 12,
    status: "playable",
    ollie: {
      intro: "Today we learn to spot free pieces. Chess players call them 'hanging'.",
      mistake: "That's okay. Look for a piece that nothing is protecting.",
      success: "Free piece, taken. That's how games get won.",
    },
    steps: [
      {
        id: "s11-teach",
        type: "teach",
        title: "Nobody is guarding it",
        lines: [
          "A piece is HANGING when you can take it and nothing takes you back.",
          "Before every move, look at your opponent's pieces and ask: is anything guarding that?",
          "Most beginner games are decided by free pieces. Not by clever plans.",
        ],
      },
      {
        id: "s11-drill",
        type: "puzzle_drill",
        title: "Take what's free",
        drill: {
          passRequired: 2,
          puzzles: [
            {
              id: "s11-p1",
              fen: "4k3/8/8/3n4/8/8/8/3RK3 w - - 0 1",
              prompt: "Something is hanging. Take it.",
              solutionMoves: ["Rxd5"],
              hint: "Your rook and the knight are on the same line.",
            },
            {
              id: "s11-p2",
              fen: "4k3/8/2b5/8/8/8/8/2R1K3 w - - 0 1",
              prompt: "Take the free piece.",
              solutionMoves: ["Rxc6"],
              hint: "Straight up the column.",
            },
            {
              id: "s11-p3",
              fen: "4k3/8/8/8/3q4/8/8/3RK3 w - - 0 1",
              prompt: "The biggest one yet. Take it.",
              solutionMoves: ["Rxd4"],
              hint: "That is a Queen, and nothing is guarding her.",
            },
          ],
          remedial: {
            id: "s11-r1",
            fen: "4k3/8/8/3n4/8/8/8/3RK3 w - - 0 1",
            prompt: "One more. Take the knight.",
            solutionMoves: ["Rxd5"],
            hint: "Rook goes straight up and takes.",
          },
          remedialTeach: "Here is the whole trick: put your finger on the enemy piece and ask 'if I take it, what takes me back?'. If the answer is nothing, take it.",
        },
      },
      {
        id: "s11-recap",
        type: "recap",
        title: "You can spot free pieces",
        learned: ["A hanging piece is one nothing is guarding.", "Checking for free pieces wins games."],
        nextTeaser: "Next: the sneakiest trick in chess.",
      },
    ],
  },
  {
    id: "s12-fork-festival",
    number: 12,
    moduleId: "m5-king",
    title: "Fork Festival",
    subtitle: "One piece. Two targets. No escape.",
    skillTags: ["fork"],
    starred: true,
    estimatedMinutes: 20,
    status: "playable",
    ollie: {
      intro: "Today you learn the sneakiest trick in chess.",
      mistake: "That's okay. A fork attacks TWO things at once — keep looking for the second one.",
      success: "Two at once. They can only save one.",
    },
    steps: [
      {
        id: "s12-teach",
        type: "teach",
        title: "Attack two things at once",
        lines: [
          "A FORK is one piece attacking two things at the same time.",
          "Your opponent only gets one move. They save one — you take the other.",
          "Knights are the best forkers in chess, because nobody sees them coming.",
        ],
      },
      {
        id: "s12-drill",
        type: "puzzle_drill",
        title: "Three forks",
        drill: {
          passRequired: 2,
          puzzles: [
            {
              id: "s12-p1",
              fen: "r3k3/8/8/3N4/8/8/8/4K3 w - - 0 1",
              prompt: "Fork the King and the rook.",
              solutionMoves: ["Nc7+"],
              hint: "Find the square that attacks BOTH black pieces.",
              successLine: "WAIT — one move and you're attacking BOTH of them?!",
            },
            {
              id: "s12-p2",
              fen: "3q3k/8/8/4N3/8/8/8/4K3 w - - 0 1",
              prompt: "Fork the King and the Queen.",
              solutionMoves: ["Nf7+"],
              hint: "One square attacks the corner AND the Queen.",
              successLine: "The Queen AND the King, from one knight. That's the fork.",
            },
            {
              id: "s12-p3",
              fen: "4k3/8/3n1b2/8/4P3/8/8/4K3 w - - 0 1",
              prompt: "Even a pawn can fork. Push it.",
              solutionMoves: ["e5"],
              hint: "Move the pawn one square and look at what it attacks.",
              successLine: "Even a PAWN just forked two pieces. Nothing is safe from this trick.",
            },
          ],
          remedial: {
            id: "s12-r1",
            fen: "k7/8/8/8/q1N5/8/8/4K3 w - - 0 1",
            prompt: "One more. Fork the King and the Queen with your Knight.",
            solutionMoves: ["Nb6+"],
            hint: "There is one square that touches both of them.",
          },
          remedialTeach: "Slow it down. Put the knight on a square in your head, then ask: what does it attack from there? Keep going until one square attacks two things.",
        },
      },
      {
        id: "s12-ceremony",
        type: "ceremony",
        title: "Fork Master",
        headline: "FORK MASTER",
        lines: [
          "One piece. Two targets. They can only save one.",
          "This is the trick grown-ups fall for. Who gets it first — Papa, Mama, or a friend at school?",
        ],
        unlock: FORK_MASTER,
        epic: true,
      },
      {
        id: "s12-recap",
        type: "recap",
        title: "You can fork",
        learned: ["A fork attacks two pieces at once.", "Knights are the best forkers."],
        nextTeaser: "Next: try it on a real person.",
      },
    ],
    shareUnlock: FORK_MASTER,
  },
  {
    id: "s13-parent-mode",
    number: 13,
    moduleId: "m5-king",
    title: "Try Your Fork on a Real Person",
    subtitle: "Grab a grown-up. This one needs two of you.",
    skillTags: ["fork"],
    starred: true,
    estimatedMinutes: 18,
    status: "playable",
    ollie: {
      intro: "Today you use your fork on an actual human being. Go and find one.",
      mistake: "That's okay. Take your time — they can't rush you.",
      success: "You did that to a REAL person.",
    },
    steps: [
      {
        id: "s13-teach",
        type: "teach",
        title: "Find a grown-up",
        lines: [
          "This one needs two people and one screen.",
          "Sit next to each other. You play the board; they read their own instructions.",
          "They are not going easy on you. They just don't know what you know.",
        ],
      },
      {
        id: "s13-parent",
        type: "parent_mode",
        title: "Parent Mode",
        intro: "Hand the phone over when it says so, and take it back when it says so. That's the whole game.",
        beats: [
          {
            // The grown-up genuinely walks into it: they move their own rook
            // onto the square that completes the fork. The child is not being
            // handed a puzzle — the position they solve was created by a real
            // person sitting next to them, one move ago.
            fen: "4k3/r7/8/3N4/8/8/8/4K3 b - - 0 1",
            parentInstruction:
              "You're Black. Move your rook from a7 up to a8 — tap the rook, then tap a8. Then pass the phone back and look relaxed.",
            childGoal: "Watch what they do. Your turn is next.",
            successMove: "Ra8",
          },
          {
            fen: "r3k3/8/8/3N4/8/8/8/4K3 w - - 0 1",
            parentInstruction:
              "Now sit back and say nothing. There is one move here that attacks your King AND your rook at the same time. Let them find it — even if it takes a while.",
            childGoal: "Fork the King and the rook.",
            successMove: "Nc7+",
          },
        ],
        celebration: "You did that to a REAL person.",
      },
      {
        id: "s13-ceremony",
        type: "ceremony",
        title: "Real opponent",
        headline: "YOU BEAT A REAL PERSON TO IT",
        lines: ["Not a computer. A person, sitting right there.", "That is what chess is actually for."],
        unlock: REAL_OPPONENT,
        epic: true,
      },
      {
        id: "s13-recap",
        type: "recap",
        title: "You forked a human",
        learned: ["You used a real tactic against a real person.", "You can teach someone this."],
        nextTeaser: "Next: two more traps — pins and skewers.",
      },
    ],
    shareUnlock: REAL_OPPONENT,
  },
  {
    id: "s14-pins-skewers",
    number: 14,
    moduleId: "m5-king",
    title: "Pins and Skewers",
    subtitle: "Freeze it, or push it off.",
    skillTags: ["pin", "skewer"],
    starred: false,
    estimatedMinutes: 14,
    status: "playable",
    ollie: {
      intro: "Today: two more traps. Both use a straight line through two pieces.",
      mistake: "That's okay. Line up your piece so TWO of theirs are on the same road.",
      success: "Frozen. It can't move without giving up the King.",
    },
    steps: [
      {
        id: "s14-teach",
        type: "teach",
        title: "Two pieces on one line",
        lines: [
          "A PIN freezes a piece: if it moves, the King behind it gets attacked. So it can't move.",
          "A SKEWER is the same line the other way round: you attack the big piece FIRST, and when it moves you take the one behind.",
          "Both need your rook, bishop or queen looking straight through two enemy pieces.",
        ],
      },
      {
        id: "s14-drill",
        type: "puzzle_drill",
        title: "Freeze it",
        drill: {
          passRequired: 2,
          puzzles: [
            {
              id: "s14-p1",
              fen: "4k3/8/8/4n3/8/8/8/R5K1 w - - 0 1",
              prompt: "Pin the knight so it cannot move.",
              solutionMoves: ["Re1"],
              hint: "Put your rook on the same column as the knight AND the King.",
            },
            {
              id: "s14-p2",
              fen: "1k5r/8/8/8/8/8/8/R5K1 w - - 0 1",
              prompt: "Skewer: check the King so that the rook behind falls.",
              solutionMoves: ["Ra8+"],
              hint: "Get on the top row. The King must move — and then look what's left.",
            },
            {
              id: "s14-p3",
              fen: "4k3/8/8/4q3/8/8/8/R5K1 w - - 0 1",
              prompt: "Pin the Queen to her King.",
              solutionMoves: ["Re1"],
              hint: "Same column as the Queen and the King.",
            },
          ],
          remedial: {
            id: "s14-r1",
            fen: "4k3/8/8/4n3/8/8/8/R5K1 w - - 0 1",
            prompt: "One more. Pin the knight.",
            solutionMoves: ["Re1"],
            hint: "Slide the rook across to the King's column.",
          },
          remedialTeach: "Look for the enemy King first. Then look for a piece standing on the same line as him. Then put your rook on that line.",
        },
      },
      {
        id: "s14-recap",
        type: "recap",
        title: "You know pins and skewers",
        learned: ["A pin freezes a piece in front of the King.", "A skewer forces the big piece to move first."],
        nextTeaser: "Next: the trap that lives on the back row.",
      },
    ],
  },
  {
    id: "s15-back-rank",
    number: 15,
    moduleId: "m5-king",
    title: "Back-Rank Ideas",
    subtitle: "The King trapped by his own pawns.",
    skillTags: ["back_rank"],
    starred: false,
    estimatedMinutes: 12,
    status: "playable",
    ollie: {
      intro: "Today: the trap that catches grown-ups more than anyone.",
      mistake: "That's okay. Look at the King's escape squares — are there any?",
      success: "Trapped by his own pawns. Beautiful.",
    },
    steps: [
      {
        id: "s15-teach",
        type: "teach",
        title: "His own pawns are in the way",
        lines: [
          "A King who has castled is safe — usually.",
          "But if his three pawns are still sitting in front of him, he has NO squares to run to.",
          "Bring a rook or queen to that back row and it is over.",
        ],
      },
      {
        id: "s15-drill",
        type: "puzzle_drill",
        title: "Back row",
        drill: {
          passRequired: 2,
          puzzles: [
            {
              id: "s15-p1",
              fen: "6k1/5ppp/8/8/8/8/8/R5K1 w - - 0 1",
              prompt: "Checkmate in one move.",
              solutionMoves: ["Ra8#"],
              hint: "Get on the back row. The King has nowhere to go.",
            },
            {
              id: "s15-p2",
              fen: "6k1/5ppp/8/8/8/8/8/1R4K1 w - - 0 1",
              prompt: "Checkmate in one move.",
              solutionMoves: ["Rb8#"],
              hint: "Same idea, different rook.",
            },
            {
              id: "s15-p3",
              fen: "6k1/5ppp/8/8/8/8/8/Q5K1 w - - 0 1",
              prompt: "Now with the Queen. Checkmate in one.",
              solutionMoves: ["Qa8#"],
              hint: "The Queen can reach the back row too.",
            },
          ],
          remedial: {
            id: "s15-r1",
            fen: "6k1/5ppp/8/8/8/8/8/R5K1 w - - 0 1",
            prompt: "One more. Mate on the back row.",
            solutionMoves: ["Ra8#"],
            hint: "Slide your rook all the way to the top row.",
          },
          remedialTeach: "Count the King's escape squares out loud. Every one is blocked by his own pawn. That means any check on the back row is checkmate.",
        },
      },
      {
        id: "s15-recap",
        type: "recap",
        title: "You know the back-rank trap",
        learned: ["A King behind his own pawns cannot escape.", "A rook or queen on the back row can be checkmate."],
        nextTeaser: "Next: a check-up on everything you've learned.",
      },
    ],
  },
  {
    id: "s16-boss-tactics",
    number: 16,
    moduleId: "m5-king",
    title: "Boss Battle: Tactics Check",
    subtitle: "Fork, pin, back rank — all mixed up.",
    skillTags: ["fork", "pin", "back_rank"],
    starred: false,
    estimatedMinutes: 14,
    status: "playable",
    ollie: {
      intro: "No new tricks today. Just the ones you already know, shuffled.",
      mistake: "That's okay. Ask yourself which trick this one is.",
      success: "You knew which trick it was. That's the hard part.",
    },
    steps: [
      {
        id: "s16-exam",
        type: "exam",
        title: "Tactics check",
        intro: "Three positions. Each one is a trick you already know — you just have to spot which.",
        drill: {
          passRequired: 2,
          puzzles: [
            {
              id: "s16-p1",
              fen: "3q3k/8/8/4N3/8/8/8/4K3 w - - 0 1",
              prompt: "Which trick is this?",
              solutionMoves: ["Nf7+"],
              hint: "One piece, two targets.",
            },
            {
              id: "s16-p2",
              fen: "6k1/5ppp/8/8/8/8/8/R5K1 w - - 0 1",
              prompt: "Which trick is this?",
              solutionMoves: ["Ra8#"],
              hint: "Look at his escape squares.",
            },
            {
              id: "s16-p3",
              fen: "4k3/8/8/4q3/8/8/8/R5K1 w - - 0 1",
              prompt: "Which trick is this?",
              solutionMoves: ["Re1"],
              hint: "Two enemy pieces on one line.",
            },
          ],
          remedial: {
            id: "s16-r1",
            fen: "r3k3/8/8/3N4/8/8/8/4K3 w - - 0 1",
            prompt: "One more. Find the fork.",
            solutionMoves: ["Nc7+"],
            hint: "The Knight can touch the King and the rook from one square.",
          },
          remedialTeach: "When you are stuck, run the list: is anything free? Can I attack two things? Are two of their pieces on one line? Is the King stuck on the back row?",
        },
      },
      {
        id: "s16-recap",
        type: "recap",
        title: "You passed the tactics check",
        learned: ["You can tell a fork from a pin from a back-rank mate."],
        nextTeaser: "Next: what to do when it's YOUR King in trouble.",
      },
    ],
  },

  // ────────────────────────── ACT 3 — I PLAY FOR REAL ──────────────────────────
  {
    id: "s17-escape-check",
    number: 17,
    moduleId: "m6-tactics",
    title: "Escape from Check",
    subtitle: "Three ways out. Always.",
    skillTags: ["escape_check"],
    starred: false,
    estimatedMinutes: 12,
    status: "playable",
    ollie: {
      intro: "Today it's your King in trouble. There are only three ways out — and you know all of them.",
      mistake: "That's okay. Move him, block it, or take the attacker.",
      success: "Out of check, and nothing lost.",
    },
    steps: [
      {
        id: "s17-teach",
        type: "teach",
        title: "Move, block, take",
        lines: [
          "When you are in check there are exactly three legal answers.",
          "MOVE the King somewhere safe. BLOCK the line with another piece. Or TAKE the attacker.",
          "If none of the three work — that is checkmate.",
        ],
      },
      {
        id: "s17-drill",
        type: "puzzle_drill",
        title: "Get out of check",
        drill: {
          passRequired: 2,
          puzzles: [
            {
              id: "s17-p1",
              fen: "4rk2/8/8/8/8/8/8/4K3 w - - 0 1",
              prompt: "You are in check. Move your King to safety.",
              solutionMoves: ["Kd1", "Kf1", "Kd2", "Kf2"],
              hint: "Step off the column the rook is attacking.",
            },
            {
              id: "s17-p2",
              fen: "5k2/8/8/8/8/8/4r3/4K3 w - - 0 1",
              prompt: "You are in check. Take the attacker.",
              solutionMoves: ["Kxe2"],
              hint: "The rook is right next to your King, and nothing is guarding it.",
            },
            {
              id: "s17-p3",
              fen: "4rk2/8/8/8/8/8/R7/4K3 w - - 0 1",
              prompt: "You are in check. BLOCK it — put something in the way.",
              solutionMoves: ["Re2"],
              hint: "Slide your rook across so it stands between the black rook and your King.",
            },
          ],
          remedial: {
            id: "s17-r1",
            fen: "4rk2/8/8/8/8/8/8/4K3 w - - 0 1",
            prompt: "One more. Just move the King out of the way.",
            solutionMoves: ["Kd1", "Kf1", "Kd2", "Kf2"],
            hint: "Any square that is not on the rook's column.",
          },
          remedialTeach: "Say the three out loud every time: MOVE, BLOCK, TAKE. On this one, the easiest is MOVE.",
        },
      },
      {
        id: "s17-recap",
        type: "recap",
        title: "You can escape check",
        learned: ["There are three ways out of check: move, block, take.", "No way out means checkmate."],
        nextTeaser: "Next: the moment you've been waiting for.",
      },
    ],
  },
  {
    id: "s18-first-checkmate",
    number: 18,
    moduleId: "m6-tactics",
    title: "Your First Checkmate",
    subtitle: "The move that ends the game.",
    skillTags: ["checkmate"],
    starred: true,
    estimatedMinutes: 18,
    status: "playable",
    ollie: {
      intro: "Today you finish a game. Not draw it, not win a piece — finish it.",
      mistake: "That's okay. Checkmate means he has NO square left. Check every escape.",
      success: "That's checkmate. The game is over and you ended it.",
    },
    steps: [
      {
        id: "s18-teach",
        type: "teach",
        title: "Check he can't answer",
        lines: [
          "CHECKMATE is a check with no way out. Not move, not block, not take.",
          "That's it. That's the whole game.",
          "You already know all three escapes — so you know how to take them away.",
        ],
      },
      {
        id: "s18-guided",
        type: "guided_board",
        title: "Deliver checkmate",
        fen: "6k1/5ppp/8/8/8/8/8/Q5K1 w - - 0 1",
        goal: "One move. End the game.",
        acceptMoves: ["Qa8#"],
        hintLadder: [
          "His own pawns are blocking every escape square.",
          "So any check on the top row finishes it.",
          "Tap the Queen on a1, then tap a8.",
        ],
        onWrong: "That's a check — but he can still get out of it. Find the one he cannot answer.",
      },
      {
        id: "s18-drill",
        type: "puzzle_drill",
        title: "Two more mates",
        drill: {
          passRequired: 1,
          puzzles: [
            {
              id: "s18-p1",
              fen: "6k1/5ppp/8/8/8/8/8/R5K1 w - - 0 1",
              prompt: "Checkmate in one.",
              solutionMoves: ["Ra8#"],
              hint: "The back row again.",
            },
            {
              id: "s18-p2",
              fen: "6k1/5ppp/8/8/8/8/8/1R4K1 w - - 0 1",
              prompt: "Checkmate in one.",
              solutionMoves: ["Rb8#"],
              hint: "Same row, different rook.",
            },
          ],
          remedial: {
            id: "s18-r1",
            fen: "6k1/5ppp/8/8/8/8/8/Q5K1 w - - 0 1",
            prompt: "One more. Finish it with the Queen.",
            solutionMoves: ["Qa8#"],
            hint: "Straight up the left edge to the top row.",
          },
          remedialTeach: "Before you play a check, ask the three questions for HIM: can he move? can he block? can he take? If all three are no, it's mate.",
        },
      },
      {
        id: "s18-ceremony",
        type: "ceremony",
        title: "First checkmate",
        headline: "CHECKMATE",
        lines: [
          "Check says: careful. Checkmate says: it's over. You just told him it was over.",
          "Every player alive remembers their first one. This was yours.",
        ],
        unlock: FIRST_CHECKMATE,
        epic: true,
      },
      {
        id: "s18-recap",
        type: "recap",
        title: "You delivered checkmate",
        learned: ["Checkmate is a check with no escape.", "You found one yourself."],
        nextTeaser: "Next: the strangest move in chess.",
      },
    ],
    shareUnlock: FIRST_CHECKMATE,
  },
  {
    id: "s19-castling",
    number: 19,
    moduleId: "m6-tactics",
    title: "Castling",
    subtitle: "Two pieces. One move. Very strange.",
    skillTags: ["castling"],
    starred: false,
    estimatedMinutes: 10,
    status: "playable",
    ollie: {
      intro: "Today: the only move in chess where two pieces move at once.",
      mistake: "That's okay. Castling needs the squares between them to be empty.",
      success: "King safe, rook working. Best move in the opening.",
    },
    steps: [
      {
        id: "s19-teach",
        type: "teach",
        title: "The King hides, the rook comes out",
        lines: [
          "CASTLING moves your King two squares sideways and hops the rook over him.",
          "It does two good things at once: the King gets safe, and the rook joins the game.",
          "You can only do it if neither piece has moved yet, and nothing is in between.",
        ],
      },
      {
        id: "s19-guided",
        type: "guided_board",
        title: "Castle",
        fen: "r3k2r/pppppppp/8/8/8/8/PPPPPPPP/R3K2R w KQkq - 0 1",
        goal: "Castle your King to safety.",
        acceptMoves: ["O-O", "O-O-O", "e1g1", "e1c1"],
        hintLadder: [
          "The squares between your King and rook are empty.",
          "Tap the King and look for the square two along.",
          "Tap the King on e1, then tap g1.",
        ],
        onWrong: "That's a normal move. Castling is special — move the KING two squares toward a rook.",
      },
      {
        id: "s19-drill",
        type: "puzzle_drill",
        title: "Both ways",
        drill: {
          passRequired: 2,
          puzzles: [
            { id: "s19-p1", fen: "4k3/8/8/8/8/8/8/4K2R w K - 0 1", prompt: "Castle on the short side.", solutionMoves: ["O-O", "e1g1"], hint: "King two squares toward the rook on the right." },
            { id: "s19-p2", fen: "4k3/8/8/8/8/8/8/R3K3 w Q - 0 1", prompt: "Now the long side. Castle toward the far rook.", solutionMoves: ["O-O-O", "e1c1"], hint: "King two squares toward the rook on the LEFT — it's still only two." },
            { id: "s19-p3", fen: "4k3/8/8/8/8/8/8/R3KB1R w KQ - 0 1", prompt: "One side is blocked. Castle the side that works.", solutionMoves: ["O-O-O", "e1c1"], hint: "The Bishop is in the way on the right. Look left." },
          ],
          remedial: { id: "s19-r1", fen: "r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 0 1", prompt: "One more. Castle either way.", solutionMoves: ["O-O", "O-O-O", "e1g1", "e1c1"], hint: "Tap the King, then tap two squares to the side." },
          remedialTeach: "Castling is always the same move: King TWO squares sideways, rook hops over. Left or right. Nothing between them, and neither piece has moved yet.",
        },
      },
      {
        id: "s19-recap",
        type: "recap",
        title: "You can castle",
        learned: ["Castling moves the King and rook together.", "It makes the King safe early."],
        nextTeaser: "Next: how to stop giving pieces away.",
      },
    ],
  },
  {
    id: "s20-dont-hang",
    number: 20,
    moduleId: "m6-tactics",
    title: "Don't Hang Your Pieces",
    subtitle: "Check before you move.",
    skillTags: ["hanging_pieces", "planning"],
    starred: false,
    estimatedMinutes: 12,
    status: "playable",
    ollie: {
      intro: "Today we stop giving pieces away for free. This one wins more games than any trick.",
      mistake: "That's okay. Ask what they can take AFTER your move.",
      success: "You checked before you moved. That is what good players do.",
    },
    steps: [
      {
        id: "s20-teach",
        type: "teach",
        title: "The question before every move",
        lines: [
          "Before you move, ask one question: if I put my piece there, can anything take it?",
          "If the answer is yes and nothing takes back — pick a different square.",
          "That single habit is worth more than every trick in this course.",
        ],
      },
      {
        id: "s20-drill",
        type: "puzzle_drill",
        title: "Take the safe one",
        drill: {
          passRequired: 2,
          puzzles: [
            {
              id: "s20-p1",
              fen: "4k3/8/8/3n1b2/8/8/8/3RK3 w - - 0 1",
              prompt: "One of these is free. Take that one.",
              solutionMoves: ["Rxd5"],
              hint: "Check what guards each piece before you take.",
            },
            {
              id: "s20-p2",
              fen: "4k3/8/2b5/8/8/8/8/2R1K3 w - - 0 1",
              prompt: "Take the free piece.",
              solutionMoves: ["Rxc6"],
              hint: "Nothing is guarding it.",
            },
            {
              id: "s20-p3",
              fen: "4k3/8/8/8/3q4/8/8/3RK3 w - - 0 1",
              prompt: "Take the free piece.",
              solutionMoves: ["Rxd4"],
              hint: "Even a Queen can hang.",
            },
          ],
          remedial: {
            id: "s20-r1",
            fen: "4k3/8/8/3n4/8/8/8/3RK3 w - - 0 1",
            prompt: "One more. Take the knight — it is not guarded.",
            solutionMoves: ["Rxd5"],
            hint: "Straight up the column.",
          },
          remedialTeach: "Point at the piece you want to take. Now point at everything of theirs that could take you back. If your finger finds nothing, it's safe.",
        },
      },
      {
        id: "s20-recap",
        type: "recap",
        title: "You check before you move",
        learned: ["You ask what can be taken before moving.", "This habit wins more games than tricks."],
        nextTeaser: "Next: a full game, with less help.",
      },
    ],
  },
  {
    id: "s21-full-game",
    number: 21,
    moduleId: "m7-full-game",
    title: "Play a Full Game",
    subtitle: "Longer, and mostly on your own.",
    skillTags: ["full_game"],
    starred: false,
    estimatedMinutes: 20,
    status: "playable",
    ollie: {
      intro: "Today you play a longer game and I say much less. That's on purpose.",
      mistake: "That's okay. Keep playing — one bad move is not a lost game.",
      success: "You did most of that yourself.",
    },
    steps: [
      {
        id: "s21-teach",
        type: "teach",
        title: "Your own game",
        lines: [
          "Same rules as before: middle pawns, then knights and bishops, then castle.",
          "Look for free pieces every single move.",
          "Hints are still here if you need them — but try one move without first.",
        ],
      },
      {
        id: "s21-bot",
        type: "bot_match",
        title: "A full game",
        goal: "Play sixteen of your own moves.",
        movesRequired: 16,
        hintsAllowed: true,
      },
      {
        id: "s21-recap",
        type: "recap",
        title: "You played a full game",
        learned: ["You played a long game with much less help."],
        nextTeaser: "Next: how to start a game well, every time.",
      },
    ],
  },
  {
    id: "s22-opening-ideas",
    number: 22,
    moduleId: "m7-full-game",
    title: "Opening Ideas",
    subtitle: "Three rules. No memorising.",
    skillTags: ["opening_principles"],
    starred: false,
    estimatedMinutes: 12,
    status: "playable",
    ollie: {
      intro: "Today: how to start a game. Not memorised moves — just three ideas.",
      mistake: "That's okay. Middle first, then the small pieces out.",
      success: "That's a real opening move, and you know why you played it.",
    },
    steps: [
      {
        id: "s22-teach",
        type: "teach",
        title: "Middle, out, safe",
        lines: [
          "One: take the MIDDLE with a pawn. The middle is where pieces reach the most squares.",
          "Two: get your Knights and Bishops OUT before your Queen.",
          "Three: castle, so your King is SAFE.",
          "That's it. You do not need to memorise openings to play well.",
        ],
      },
      {
        id: "s22-guided-1",
        type: "guided_board",
        title: "Take the middle",
        fen: "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
        goal: "Play a middle pawn two squares forward.",
        acceptMoves: ["e4", "d4"],
        hintLadder: [
          "The middle columns are the two in the centre.",
          "Move the pawn in front of your King or your Queen.",
          "Tap e2, then tap e4.",
        ],
        onWrong: "That's legal — but it doesn't grab the middle. Try a centre pawn.",
      },
      {
        id: "s22-guided-2",
        type: "guided_board",
        title: "Get a piece out",
        fen: "rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2",
        goal: "Bring out a Knight.",
        acceptMoves: ["Nf3", "Nc3"],
        hintLadder: [
          "Knights before Queens. Always.",
          "Your Knights are the horses on the back row.",
          "Tap g1, then tap f3.",
        ],
        onWrong: "Not yet — get a KNIGHT out first. The Queen comes later.",
      },
      {
        id: "s22-recap",
        type: "recap",
        title: "You can start a game well",
        learned: ["Take the middle.", "Knights and bishops before the Queen.", "Castle early."],
        nextTeaser: "Next: keeping your King out of trouble.",
      },
    ],
  },
  {
    id: "s23-king-safety",
    number: 23,
    moduleId: "m7-full-game",
    title: "Keep Your King Safe",
    subtitle: "Get him out of the middle.",
    skillTags: ["king_safety"],
    starred: false,
    estimatedMinutes: 10,
    status: "playable",
    ollie: {
      intro: "Today: where your King should actually stand.",
      mistake: "That's okay. The middle is the dangerous place for a King.",
      success: "King tucked away. Now you can attack without worrying.",
    },
    steps: [
      {
        id: "s23-teach",
        type: "teach",
        title: "The middle is dangerous",
        lines: [
          "In the middle of the board your King is in everybody's way — and everybody's line of fire.",
          "Castling early moves him into a corner behind his own pawns.",
          "A safe King means you can attack without something horrible happening behind you.",
        ],
      },
      {
        id: "s23-guided",
        type: "guided_board",
        title: "Get him to safety",
        fen: "rnbqk2r/pppp1ppp/5n2/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 1",
        goal: "Your pieces are out. Now make your King safe.",
        acceptMoves: ["O-O", "e1g1"],
        hintLadder: [
          "Both squares between your King and rook are empty.",
          "This is the moment to castle.",
          "Tap the King on e1, then tap g1.",
        ],
        onWrong: "That's playable — but your King is still in the middle. Castle first.",
      },
      {
        id: "s23-drill",
        type: "puzzle_drill",
        title: "Safety first",
        drill: {
          passRequired: 2,
          puzzles: [
            { id: "s23-p1", fen: "r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 1", prompt: "Your pieces are out. What's the safest move?", solutionMoves: ["O-O"], hint: "Tuck the King away." },
            { id: "s23-p2", fen: "rnbq1rk1/pppp1ppp/5n2/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQ - 0 1", prompt: "They've already castled. Catch up.", solutionMoves: ["O-O"], hint: "Same move they just made." },
            { id: "s23-p3", fen: "r3k2r/pppppppp/8/8/8/8/PPPPPPPP/R3K2R w KQkq - 0 1", prompt: "Either side works here. Get him out of the middle.", solutionMoves: ["O-O", "O-O-O", "e1g1", "e1c1"], hint: "Short or long — just castle." },
          ],
          remedial: { id: "s23-r1", fen: "4k3/8/8/8/8/8/8/4K2R w K - 0 1", prompt: "One more. Castle.", solutionMoves: ["O-O", "e1g1"], hint: "King two squares to the right." },
          remedialTeach: "The middle of the board is where every attack goes through. Castling moves the King out of the road and behind a wall of pawns. When in doubt: castle.",
        },
      },
      {
        id: "s23-recap",
        type: "recap",
        title: "You keep your King safe",
        learned: ["A King in the middle is in danger.", "Castling early is almost always right."],
        nextTeaser: "Next: a game with no hints at all.",
      },
    ],
  },
  {
    id: "s24-win-without-hints",
    number: 24,
    moduleId: "m7-full-game",
    title: "Win Without Hints",
    subtitle: "Just you and the board.",
    skillTags: ["full_game", "planning"],
    starred: true,
    estimatedMinutes: 20,
    status: "playable",
    ollie: {
      intro: "NO HINTS. NO RESCUES. Just you. I'll be quiet now — show me what you've learned.",
      mistake: "That's okay. You're on your own here — trust what you know.",
      success: "You won it on your own. I didn't help once.",
    },
    steps: [
      {
        id: "s24-teach",
        type: "teach",
        title: "No hints today",
        lines: [
          "There is no hint button in this one. That is the point.",
          "You already know everything you need: middle, pieces out, castle, check for free pieces.",
          "If it goes wrong, it goes wrong. You can play it again.",
        ],
      },
      {
        id: "s24-bot",
        type: "bot_match",
        title: "No hints",
        goal: "Play sixteen of your own moves with no help at all.",
        movesRequired: 16,
        hintsAllowed: false,
        prelude: {
          headline: "NO HINTS. NO RESCUES.",
          lines: [
            "Just you.",
            "I'll be quiet now. Show me what you've learned.",
          ],
          cta: "I'm ready",
        },
      },
      {
        id: "s24-ceremony",
        type: "ceremony",
        title: "On your own",
        headline: "YOU DIDN'T NEED ME",
        lines: ["You saw it. You chose it. You played it.", "That is what an independent player looks like."],
        unlock: INDEPENDENT,
        epic: true,
      },
      {
        id: "s24-recap",
        type: "recap",
        title: "You played independently",
        learned: ["You played a whole game with no help."],
        nextTeaser: "Next: thinking a move ahead.",
      },
    ],
    shareUnlock: INDEPENDENT,
  },

  // ────────────────────── ACT 4 — I CHALLENGE SOMEONE ──────────────────────
  {
    id: "s25-planning",
    number: 25,
    moduleId: "m8-graduate",
    title: "Planning Your Moves",
    subtitle: "What are they trying to do?",
    skillTags: ["planning"],
    starred: false,
    estimatedMinutes: 12,
    status: "playable",
    ollie: {
      intro: "Today: the question good players ask that beginners don't.",
      mistake: "That's okay. Ask what THEIR last move was trying to do.",
      success: "You saw their idea before it happened.",
    },
    steps: [
      {
        id: "s25-teach",
        type: "teach",
        title: "Their move had a reason",
        lines: [
          "Beginners look at their own pieces. Good players look at their opponent's last move.",
          "Every move they make is trying to do something. Ask what.",
          "Then stop it — or do something bigger.",
        ],
      },
      {
        id: "s25-drill",
        type: "puzzle_drill",
        title: "Spot the idea",
        drill: {
          passRequired: 2,
          puzzles: [
            {
              id: "s25-p1",
              fen: "r3k3/8/8/3N4/8/8/8/4K3 w - - 0 1",
              prompt: "Find the strongest move.",
              solutionMoves: ["Nc7+"],
              hint: "Two targets, one piece.",
            },
            {
              id: "s25-p2",
              fen: "4k3/8/8/4q3/8/8/8/R5K1 w - - 0 1",
              prompt: "Find the strongest move.",
              solutionMoves: ["Re1"],
              hint: "Line them up.",
            },
            {
              id: "s25-p3",
              fen: "6k1/5ppp/8/8/8/8/8/1R4K1 w - - 0 1",
              prompt: "Find the strongest move.",
              solutionMoves: ["Rb8#"],
              hint: "Count his escape squares.",
            },
          ],
          remedial: {
            id: "s25-r1",
            fen: "4k3/8/8/3n4/8/8/8/3RK3 w - - 0 1",
            prompt: "One more. What is the best move here?",
            solutionMoves: ["Rxd5"],
            hint: "Something is free.",
          },
          remedialTeach: "Run the checklist every time: free piece? fork? two on a line? King stuck on the back row? One of those four is nearly always the answer.",
        },
      },
      {
        id: "s25-recap",
        type: "recap",
        title: "You can plan",
        learned: ["You look at your opponent's last move.", "You run a checklist before choosing."],
        nextTeaser: "Next: the King finally gets to be strong.",
      },
    ],
  },
  {
    id: "s26-endgame-king",
    number: 26,
    moduleId: "m8-graduate",
    title: "Endgame King Power",
    subtitle: "When the board empties, he walks out.",
    skillTags: ["endgame_king"],
    starred: false,
    estimatedMinutes: 12,
    status: "playable",
    ollie: {
      intro: "Today your King stops hiding. At the end of a game he becomes a fighter.",
      mistake: "That's okay. Walk him TOWARD the middle, not away.",
      success: "That's it. The King leads at the end.",
    },
    steps: [
      {
        id: "s26-teach",
        type: "teach",
        title: "He comes out at the end",
        lines: [
          "Early in the game the King hides, because there are pieces everywhere.",
          "When most pieces are gone, there is nothing left to be scared of.",
          "Now he walks out and helps — usually by escorting a pawn to the far end.",
        ],
      },
      {
        id: "s26-guided",
        type: "guided_board",
        title: "Walk the King out",
        fen: "8/8/8/3k4/8/8/3PK3/8 w - - 0 1",
        goal: "Step your King forward to lead the pawn.",
        acceptMoves: ["Kd3", "Ke3", "Kf3"],
        hintLadder: [
          "Don't push the pawn yet. The King goes first.",
          "Move him up the board, toward the enemy King.",
          "Tap your King on e2, then tap e3.",
        ],
        onWrong: "That's legal — but at the end the KING leads. Move him forward first.",
      },
      {
        id: "s26-drill",
        type: "puzzle_drill",
        title: "Walk it home",
        drill: {
          passRequired: 2,
          puzzles: [
            { id: "s26-p1", fen: "8/8/8/3k4/8/4K3/3P4/8 w - - 0 1", prompt: "The King is ahead now. Bring the pawn up behind him.", solutionMoves: ["d4", "d3"], hint: "Push the pawn — your King is guarding the square." },
            { id: "s26-p2", fen: "8/3P4/8/8/8/8/8/k3K3 w - - 0 1", prompt: "The pawn made it. Finish the journey.", solutionMoves: ["d8=Q", "d8=Q+", "d7d8q"], hint: "One more step and it becomes a Queen." },
            { id: "s26-p3", fen: "8/8/8/8/2k5/8/8/3QK3 w - - 0 1", prompt: "With a Queen, the end is near. Give check.", solutionMoves: ["Qd4+", "Qc2+", "Qa4+", "Qc1+", "Qd3+"], hint: "Any square where the Queen looks at the King." },
          ],
          remedial: { id: "s26-r1", fen: "8/8/8/3k4/8/8/3PK3/8 w - - 0 1", prompt: "One more. King first — step him forward.", solutionMoves: ["Kd3", "Ke3", "Kf3"], hint: "Move the King, not the pawn." },
          remedialTeach: "At the end of the game the King is a fighter. He walks in FRONT of the pawn to clear the way, and the pawn follows him home. King first, pawn second.",
        },
      },
      {
        id: "s26-recap",
        type: "recap",
        title: "You can use the King at the end",
        learned: ["The King is strong once the board is empty.", "The King leads the pawn home."],
        nextTeaser: "Next: two players, one phone.",
      },
    ],
  },
  {
    id: "s27-pass-and-play",
    number: 27,
    moduleId: "m8-graduate",
    title: "Pass-and-Play Practice",
    subtitle: "Two people. One phone. No computer.",
    skillTags: ["full_game"],
    starred: false,
    estimatedMinutes: 18,
    status: "playable",
    ollie: {
      intro: "Today there is no computer. Just two humans and one board.",
      mistake: "That's okay. Take your time — the other player can wait.",
      success: "You played a real person, all the way through.",
    },
    steps: [
      {
        id: "s27-teach",
        type: "teach",
        title: "Take turns",
        lines: [
          "Find someone — a grown-up, a brother or sister, a friend.",
          "One of you plays White, one plays Black. Pass the phone after each move.",
          "Nobody else can see this game. It is just the two of you.",
        ],
      },
      {
        id: "s27-pass",
        type: "pass_and_play",
        title: "Pass and play",
        intro: "White moves first. Pass the phone after every move.",
        goal: "Play a game all the way to the end — or until you both decide to stop.",
      },
      {
        id: "s27-recap",
        type: "recap",
        title: "You played a person",
        learned: ["You played a whole game against a real human on one device."],
        nextTeaser: "Next: teach it to someone else.",
      },
    ],
  },
  {
    id: "s28-teach-a-friend",
    number: 28,
    moduleId: "m8-graduate",
    title: "Teach a Friend",
    subtitle: "You explain. They play.",
    skillTags: ["teaching_others"],
    starred: false,
    estimatedMinutes: 15,
    status: "playable",
    ollie: {
      intro: "Today you are the teacher. You know enough now — that is not flattery, it is true.",
      mistake: "That's okay. Explaining is harder than playing. Keep going.",
      success: "You taught someone chess. That is a different level of knowing it.",
    },
    steps: [
      {
        id: "s28-teach",
        type: "teach",
        title: "Your turn to be Ollie",
        lines: [
          "Find someone who does not know chess, and teach them three things.",
          "One: how the pieces move. Two: what check means. Three: your favourite trick — the fork.",
          "If you can explain it, you know it.",
        ],
      },
      {
        id: "s28-pass",
        type: "pass_and_play",
        title: "Play the person you taught",
        intro: "Now play them. Go gently — they only just learned.",
        goal: "Play a game against the person you just taught.",
      },
      {
        id: "s28-recap",
        type: "recap",
        title: "You taught someone",
        learned: ["You explained chess to another person.", "You played the person you taught."],
        nextTeaser: "Next: getting ready for Graduation.",
      },
    ],
  },
  {
    id: "s29-graduation-prep",
    number: 29,
    moduleId: "m8-graduate",
    title: "Graduation Prep",
    subtitle: "Everything you know, in one place.",
    skillTags: ["planning", "full_game"],
    starred: false,
    estimatedMinutes: 12,
    status: "playable",
    ollie: {
      intro: "Tomorrow you play for real. I'm proud of you.",
      mistake: "That's okay. You've done all of these before.",
      success: "You still know all of it. You're ready.",
    },
    steps: [
      {
        id: "s29-teach",
        type: "teach",
        title: "What you can do now",
        lines: [
          "You know how every piece moves, and what each one is good at.",
          "You know check, checkmate, and the three ways out.",
          "You know forks, pins, skewers and the back rank — and you have used them on a real person.",
        ],
      },
      {
        id: "s29-exam",
        type: "exam",
        title: "Final check",
        intro: "Three positions. Nothing new. Just proof.",
        drill: {
          passRequired: 2,
          puzzles: [
            {
              id: "s29-p1",
              fen: "3q3k/8/8/4N3/8/8/8/4K3 w - - 0 1",
              prompt: "Find it.",
              solutionMoves: ["Nf7+"],
              hint: "Fork.",
            },
            {
              id: "s29-p2",
              fen: "6k1/5ppp/8/8/8/8/8/Q5K1 w - - 0 1",
              prompt: "Find it.",
              solutionMoves: ["Qa8#"],
              hint: "Back rank.",
            },
            {
              id: "s29-p3",
              fen: "4k3/8/8/4n3/8/8/8/R5K1 w - - 0 1",
              prompt: "Find it.",
              solutionMoves: ["Re1"],
              hint: "Pin.",
            },
          ],
          remedial: {
            id: "s29-r1",
            fen: "6k1/5ppp/8/8/8/8/8/R5K1 w - - 0 1",
            prompt: "One more. Finish the game.",
            solutionMoves: ["Ra8#"],
            hint: "Back row.",
          },
          remedialTeach: "You have solved every one of these before. Run the checklist: free piece, fork, two on a line, back rank.",
        },
      },
      {
        id: "s29-recap",
        type: "recap",
        title: "You are ready",
        learned: ["You proved every skill in the course."],
        nextTeaser: "Tomorrow: Graduation Day.",
      },
    ],
  },
  {
    id: "s30-graduation-duel",
    number: 30,
    moduleId: "m8-graduate",
    title: "Graduation Duel",
    subtitle: "A real person. No hints. Today you graduate.",
    skillTags: ["full_game", "teaching_others"],
    starred: true,
    estimatedMinutes: 25,
    status: "playable",
    ollie: {
      intro: "Today is Graduation Day.",
      mistake: "That's okay. Win or lose, you graduate today. That was always the deal.",
      success: "You're not learning chess anymore. You're a chess player.",
    },
    steps: [
      {
        id: "s30-ceremony-open",
        type: "ceremony",
        title: "Graduation Day",
        headline: "TODAY IS DIFFERENT",
        lines: [
          "Today, you graduate.",
          "Thirty sessions ago you had not played a game of chess.",
          "Today you play a real person, with no hints, and then you graduate. Win or lose. That was always the deal.",
        ],
        epic: true,
      },
      {
        id: "s30-recap-montage",
        type: "recap",
        title: "How far you came",
        montage: true,
        learned: [
          "THE PAWN — You learned that even the smallest piece can grow into the strongest one.",
          "THE KNIGHT — You learned to see the move nobody else sees coming.",
          "THE KING — You learned what actually matters, and how to protect it.",
          "TACTICS — You learned to spot the opportunity before your opponent does.",
          "REAL PLAY — You learned to trust yourself, with nobody helping.",
        ],
        nextTeaser: "One final game.",
      },
      {
        id: "s30-duel",
        type: "pass_and_play",
        title: "The Graduation Duel",
        intro: "Find your opponent. A grown-up, a sibling, a friend — anyone who will sit down with you.",
        goal: "Play one game, all the way through. No hints. This is the real thing.",
        prelude: {
          headline: "GRADUATION DUEL",
          lines: [
            "NO HINTS. NO RESCUES. JUST CHESS.",
            "Find your opponent — a grown-up, a sibling, a friend. Sit down together, on this device. Nobody else sees this game.",
            "You're White. They're Black.",
          ],
          cta: "Begin the duel",
        },
        resultLines: {
          win: "YOU WON THE GRADUATION DUEL! You saw it, you chose it, you played it — start to finish.",
          loss: "That was a real game. Real chess players lose games too. And they play another.",
          draw: "Neither of you could break through. That is a real result against a real opponent.",
        },
      },
      {
        id: "s30-ceremony",
        type: "ceremony",
        title: "Graduation",
        headline: "CHESS SCHOOL GRADUATE",
        lines: [
          "You graduated because you learned how to PLAY.",
          "You're not learning chess anymore. You're a chess player.",
          "Go and challenge someone.",
        ],
        unlock: GRADUATE,
        epic: true,
      },
    ],
    shareUnlock: GRADUATE,
  },
];

/** Total sessions in the course — never a hardcoded 30 anywhere else. */
export const TOTAL_SESSIONS = SCHOOL_SESSIONS.length;

export function getSession(number: number): SchoolSession | null {
  return SCHOOL_SESSIONS.find((s) => s.number === number) ?? null;
}

export function getSessionById(id: string): SchoolSession | null {
  return SCHOOL_SESSIONS.find((s) => s.id === id) ?? null;
}
