import type { CourseLesson } from "@/lib/academy/courseTypes";

/**
 * The Strategy course — how to think when there is no tactic.
 *
 * GENERATED by scripts/emit-strategy-lessons.js. Edit the prose there, not here.
 *
 * SERVER ONLY. Reached through lib/academy/courses.server.ts and served one
 * lesson at a time by /api/academy/lesson, so none of this reaches the browser.
 *
 * Every position was found by scripts/build-strategy.js, which searches real
 * positions for ones where STOCKFISH'S OWN top move is an instance of the idea
 * the lesson teaches. The answer to each exercise is therefore the engine's
 * move, not an author's opinion — which matters more here than in tactics,
 * where correctness is decidable outright.
 */
export const STRATEGY_LESSONS: CourseLesson[] = [
  {
    id: "king-safety",
    order: 1,
    title: "Get the King Out of the Centre",
    concept: "Castling is not a formality — it is usually the most valuable move available.",
    intro: "Most attacking games are decided by which king was still sitting in the centre when the position opened up. Castling is the cheapest insurance in chess, and it is the move players most often postpone for one move too long.",
    explanation: "A king on its starting square sits on the file most likely to be opened, in front of pieces that want to move. Once lines open, every enemy piece aiming at the centre is aiming at your king, and defending costs far more time than castling would have.\n\nThe practical rule is simple: once your king can go, ask hard whether anything is genuinely more urgent. Usually nothing is. The exceptions are real — a forcing tactic, an immediate threat that must be met — but they are exceptions, and the habit should be to castle rather than to find reasons not to.",
    whatToLookFor: "Can your king still castle? Are central files starting to open? If both are true, castling is probably the move.",
    examples: [
      {
        fen: "4k1r1/1p1n2q1/4p3/1p1pP1pP/1rpP2N1/4BP1P/PP6/R3K2R w KQ - 0 25",
        caption: "White to play. The move is O-O-O.",
      },
    ],
    exercises: [
      {
        fen: "rn3rk1/p1q2b1p/1p2pp2/2np3P/6P1/2P1P3/PPQNBP2/R3K2R w KQ - 0 17",
        sideToMove: "w",
        prompt: "Your king is still in the centre. Fix that.",
        solutionFrom: "e1",
        solutionTo: "c1",
        successMessage: "Correct — O-O-O. The king steps off the open lines and the rook joins the game. This is Stockfish's move here too.",
        failureMessage: "Not this one. The king is still in the centre and the position is opening up — deal with that first.",
      },
      {
        fen: "2r1k2r/3b1pp1/p4n2/Q5Bp/3Nq3/P6P/2P2PP1/4R1K1 b k - 1 28",
        sideToMove: "b",
        prompt: "Your king is still in the centre. Fix that.",
        solutionFrom: "e8",
        solutionTo: "g8",
        successMessage: "Correct — O-O. The king steps off the open lines and the rook joins the game. This is Stockfish's move here too.",
        failureMessage: "Not this one. The king is still in the centre and the position is opening up — deal with that first.",
      },
      {
        fen: "q3k2r/3p1ppp/4p3/3PP3/1bP1n3/2N5/2P1NPPP/3QK2R w Kk - 1 16",
        sideToMove: "w",
        prompt: "Your king is still in the centre. Fix that.",
        solutionFrom: "e1",
        solutionTo: "g1",
        successMessage: "Correct — O-O. The king steps off the open lines and the rook joins the game. This is Stockfish's move here too.",
        failureMessage: "Not this one. The king is still in the centre and the position is opening up — deal with that first.",
      },
    ],
    quiz: {
      question: "You can castle, and nothing is currently attacking you. What should you usually do?",
      options: ["Castle — safety is cheapest before the position opens, not after", "Wait to see which side the opponent attacks on first", "Develop one more piece, then decide"],
      correctIndex: 0,
    },
    takeaway: "When castling is available and nothing forces your hand, castle. Postponing it is the most common way good positions collapse.",
  },
  {
    id: "outposts",
    order: 2,
    title: "Outposts",
    concept: "A square no enemy pawn can ever attack is a permanent home for a knight.",
    intro: "Some squares cannot be challenged. If no enemy pawn can ever attack a square — because the pawns that would do it are gone or have already passed by — then a piece placed there can never be chased away.",
    explanation: "That permanence is what makes outposts different from merely good squares. A knight on a normal central square can be kicked by a pawn in a move or two; a knight on an outpost has to be traded off, and trading a defender usually costs the opponent something else.\n\nKnights benefit most, because they are short-range pieces whose value depends almost entirely on where they stand. A knight on a protected outpost deep in enemy territory can be worth more than a rook. Look for these squares in front of backward pawns and on half-open files, and support them with a pawn so the outpost cannot simply be exchanged away.",
    whatToLookFor: "Find a square in enemy territory where no enemy pawn can ever attack you, and check whether one of your own pawns defends it.",
    examples: [
      {
        fen: "r2qk2r/ppp5/2n1pn2/2b1p3/2N1P1pp/2PP4/PP2Q1PP/R1B1NR1K b kq - 1 14",
        caption: "Black to play. The move is Nh5.",
      },
    ],
    exercises: [
      {
        fen: "r2qkb1r/pp1b1ppp/2np1n2/4p3/2Q1P3/2PP1N2/PP2BPPP/RNB2RK1 b kq - 1 8",
        sideToMove: "b",
        prompt: "There is a square here no enemy pawn can ever attack. Put your knight on it.",
        solutionFrom: "c6",
        solutionTo: "a5",
        successMessage: "Correct — Na5. No enemy pawn can ever attack that square, and the knight is defended: it cannot be driven away.",
        failureMessage: "Not this square. Look for a square in enemy territory where no enemy pawn can ever come to attack you.",
      },
      {
        fen: "2bq1rk1/2rp1ppp/p1n5/1p1n4/8/3Q1N2/PPP2PPP/RNB1R1K1 b - - 0 15",
        sideToMove: "b",
        prompt: "There is a square here no enemy pawn can ever attack. Put your knight on it.",
        solutionFrom: "c6",
        solutionTo: "b4",
        successMessage: "Correct — Ncb4. No enemy pawn can ever attack that square, and the knight is defended: it cannot be driven away.",
        failureMessage: "Not this square. Look for a square in enemy territory where no enemy pawn can ever come to attack you.",
      },
      {
        fen: "3r2k1/5rbp/p5p1/1p2pb2/7P/P1N5/1PQ1NPP1/1K5R w - - 0 20",
        sideToMove: "w",
        prompt: "There is a square here no enemy pawn can ever attack. Put your knight on it.",
        solutionFrom: "c3",
        solutionTo: "e4",
        successMessage: "Correct — Ne4. No enemy pawn can ever attack that square, and the knight is defended: it cannot be driven away.",
        failureMessage: "Not this square. Look for a square in enemy territory where no enemy pawn can ever come to attack you.",
      },
    ],
    quiz: {
      question: "What makes a square an outpost rather than just a good square?",
      options: ["No enemy pawn can ever attack it, so a piece there cannot be driven away", "It is in the centre of the board", "It is defended by more pieces than the opponent attacks it with"],
      correctIndex: 0,
    },
    takeaway: "Before moving a knight, ask which squares the enemy pawns can never reach. Those are the squares worth aiming at.",
  },
  {
    id: "pawn-breaks",
    order: 3,
    title: "Pawn Breaks",
    concept: "Pawns are how you change a position that has stopped changing.",
    intro: "When neither side can make progress with pieces, the position is decided by pawn breaks — advances that make contact with the enemy pawn chain and force it to resolve.",
    explanation: "Pieces can only work with the lines the pawns leave them. If your rooks have no open file and your bishops no open diagonal, no amount of shuffling will help: the structure has to change first, and only a pawn can change it.\n\nA break is a pawn advance that touches the enemy structure and asks a question — capture, advance, or allow the exchange. Each answer creates something: an open file, a passed pawn, a weak square. That is the point. The skill is choosing a break that opens lines for pieces you have already placed well, and timing it for when you are ready rather than when it first becomes possible.",
    whatToLookFor: "Which of your pawns can advance to make contact with an enemy pawn? What line does it open, and is a piece of yours already aiming down it?",
    examples: [
      {
        fen: "r2qr1k1/pppnppbp/3p1np1/8/2PP1B2/3BPN1P/PP3PP1/R2Q1RK1 b - - 0 10",
        caption: "Black to play. The move is e5.",
      },
    ],
    exercises: [
      {
        fen: "r1bq1rk1/pp1pbppp/5n2/2p5/2BpP3/3P1Q2/PPP1NPPP/R1B2RK1 b - - 1 9",
        sideToMove: "b",
        prompt: "The position is locked. Find the pawn advance that breaks it open.",
        solutionFrom: "d7",
        solutionTo: "d5",
        successMessage: "Correct — d5. The pawn makes contact with the enemy structure and forces it to resolve. Stockfish agrees this is the move.",
        failureMessage: "Not this move. Look for the pawn advance that makes contact with an enemy pawn and forces the structure to change.",
      },
      {
        fen: "7k/p1p3p1/1p5p/4b3/2P5/1P2BKP1/P4P1P/3r4 w - - 0 32",
        sideToMove: "w",
        prompt: "The position is locked. Find the pawn advance that breaks it open.",
        solutionFrom: "c4",
        solutionTo: "c5",
        successMessage: "Correct — c5. The pawn makes contact with the enemy structure and forces it to resolve. Stockfish agrees this is the move.",
        failureMessage: "Not this move. Look for the pawn advance that makes contact with an enemy pawn and forces the structure to change.",
      },
      {
        fen: "5r2/5ppk/p1p1p3/1pP1P1pr/1PpP2Rq/P4P1P/6QK/6R1 b - - 1 31",
        sideToMove: "b",
        prompt: "The position is locked. Find the pawn advance that breaks it open.",
        solutionFrom: "f7",
        solutionTo: "f6",
        successMessage: "Correct — f6. The pawn makes contact with the enemy structure and forces it to resolve. Stockfish agrees this is the move.",
        failureMessage: "Not this move. Look for the pawn advance that makes contact with an enemy pawn and forces the structure to change.",
      },
    ],
    quiz: {
      question: "Why does a blocked position usually require a pawn break rather than piece play?",
      options: ["Because only a pawn advance can change the structure that limits where pieces can go", "Because pawns are worth less, so they can be risked", "Because pieces cannot move in blocked positions"],
      correctIndex: 0,
    },
    takeaway: "When nothing is happening, stop moving pieces and ask which pawn break changes the structure in your favour.",
  },
  {
    id: "piece-activity",
    order: 4,
    title: "Piece Activity",
    concept: "A piece's value is not what it is — it is what it does.",
    intro: "A bishop that sees three squares and a bishop that sees eleven are not the same piece, whatever the material count says. Activity, not material, is what most positions turn on.",
    explanation: "Counting material is easy, which is why it is over-relied on. What decides most games is how much each piece actually controls — how many useful squares it reaches, and whether those squares matter. A rook on a closed file is close to a spectator; the same rook on an open file can dominate.\n\nSo when a position has no forcing move, the productive question is not 'what can I win?' but 'which of my pieces is doing least, and where would it do more?' That question converts an aimless position into a concrete plan, and it is available every single move.",
    whatToLookFor: "Count what each of your pieces actually controls. The one seeing fewest useful squares is the one to move.",
    examples: [
      {
        fen: "r1bq1bkr/ppp1p1pp/1n1pP3/6N1/6Q1/8/PP1P1PPP/nNBK3R w - - 0 11",
        caption: "White to play. The move is Qf5.",
      },
    ],
    exercises: [
      {
        fen: "2kr2nr/ppqbb1pp/1np2p2/3p2P1/4p2P/2PP1NQ1/PP2PPB1/RNB1K1R1 w Q - 0 12",
        sideToMove: "w",
        prompt: "No tactics here. Find the move that most increases a piece's reach.",
        solutionFrom: "c1",
        solutionTo: "f4",
        successMessage: "Correct — Bf4. That piece now controls markedly more of the board, and Stockfish rates it among the best moves here.",
        failureMessage: "Not this one. Look for the piece with the least scope, and find it a square where it sees more.",
      },
      {
        fen: "1r3rk1/pp1nqppp/5n2/2p5/2N2PP1/P1N1Q2P/1P4B1/R4RK1 b - - 0 20",
        sideToMove: "b",
        prompt: "No tactics here. Find the move that most increases a piece's reach.",
        solutionFrom: "e7",
        solutionTo: "e6",
        successMessage: "Correct — Qe6. That piece now controls markedly more of the board, and Stockfish rates it among the best moves here.",
        failureMessage: "Not this one. Look for the piece with the least scope, and find it a square where it sees more.",
      },
      {
        fen: "1r3rk1/pp1n1ppp/5n2/2p5/5PP1/P1N1N2P/1P4B1/R4RK1 b - - 0 21",
        sideToMove: "b",
        prompt: "No tactics here. Find the move that most increases a piece's reach.",
        solutionFrom: "f8",
        solutionTo: "e8",
        successMessage: "Correct — Rfe8. That piece now controls markedly more of the board, and Stockfish rates it among the best moves here.",
        failureMessage: "Not this one. Look for the piece with the least scope, and find it a square where it sees more.",
      },
    ],
    quiz: {
      question: "In a quiet position with no tactics, what is the most productive question to ask?",
      options: ["Which of my pieces is doing least, and where would it do more?", "Which piece can I trade off fastest?", "Which pawn can I push furthest?"],
      correctIndex: 0,
    },
    takeaway: "In a quiet position, improve your least active piece. It is the plan that is always available.",
  },
  {
    id: "worst-piece",
    order: 5,
    title: "Improve Your Worst Piece",
    concept: "The most reliable plan in chess, available in almost every position.",
    intro: "Strong players have a default move for positions with nothing forcing in them: find the worst-placed piece and improve it. It is not glamorous, and it wins an enormous number of games.",
    explanation: "The reason it works is that it is always available. Attacks require a target; combinations require a weakness. But there is always a piece doing less than the others, and moving it costs nothing while making every future plan easier to execute.\n\nIt also protects you from the real danger in quiet positions, which is drifting — making moves that neither improve your position nor commit to anything, until the opponent has quietly improved everything and you are worse without ever having blundered. Ask the question every move and drifting becomes impossible.",
    whatToLookFor: "Identify your least active piece first. Only then ask where it belongs.",
    examples: [
      {
        fen: "4k1r1/1R6/2n1p1n1/8/1b6/3K1NP1/PB3P2/R7 b - - 0 29",
        caption: "Black to play. The move is Rf8.",
      },
    ],
    exercises: [
      {
        fen: "1k3r2/7R/pb1p2p1/1p1N4/4P3/2P5/qP4PP/4Q2K b - - 1 32",
        sideToMove: "b",
        prompt: "One piece is doing far less than the others. Improve it.",
        solutionFrom: "a2",
        solutionTo: "c4",
        successMessage: "Correct — Qc4. That was the least active piece on the board, and it now has real scope. The engine rates this among the best moves.",
        failureMessage: "Not quite. Find the piece with the fewest available squares first, then ask where it would do more.",
      },
      {
        fen: "8/7q/P4pk1/3p1p2/3PNQp1/4P1P1/5KP1/r7 w - - 0 39",
        sideToMove: "w",
        prompt: "One piece is doing far less than the others. Improve it.",
        solutionFrom: "e4",
        solutionTo: "d6",
        successMessage: "Correct — Nd6. That was the least active piece on the board, and it now has real scope. The engine rates this among the best moves.",
        failureMessage: "Not quite. Find the piece with the fewest available squares first, then ask where it would do more.",
      },
      {
        fen: "3r2r1/1kpp3p/8/pp1Rp3/q1n1PN2/1P3pP1/2P4P/1K2RQ2 b - - 0 36",
        sideToMove: "b",
        prompt: "One piece is doing far less than the others. Improve it.",
        solutionFrom: "a4",
        solutionTo: "b4",
        successMessage: "Correct — Qb4. That was the least active piece on the board, and it now has real scope. The engine rates this among the best moves.",
        failureMessage: "Not quite. Find the piece with the fewest available squares first, then ask where it would do more.",
      },
    ],
    quiz: {
      question: "Why is 'improve your worst piece' such a reliable plan?",
      options: ["It is available in every position, even when there is no target to attack", "It always wins material within a few moves", "It forces the opponent to respond"],
      correctIndex: 0,
    },
    takeaway: "When you do not know what to do, improve your worst piece. It is never a wasted move.",
  },
];
