import { Chess } from "chess.js";
import { verifyGame, type Termination } from "./verifyGame";

/**
 * Server-side validation of a single move intent.
 *
 * Pure: no I/O. The route supplies the authoritative move list and the move the
 * player is asking to make; this decides whether it is legal and, if so, what
 * the official SAN and FEN become.
 *
 * This exists because submit_online_move writes the client's own p_fen and
 * p_san straight into the row. It checks ownership, participation, whose turn
 * it is and the clock — all correctly — but never that the move is legal or
 * that the position is real. A client could store any FEN it liked.
 *
 * So the browser now sends only { from, to, promotion }. Everything that ends
 * up in the database is generated here, from a replay of the moves the server
 * already had.
 */

export interface MoveIntent {
  from: string;
  to: string;
  promotion?: "q" | "r" | "b" | "n";
  /**
   * How many plies the client believed had been played. Optimistic
   * concurrency: if the game has moved on, the client is acting on a stale
   * board and the move is refused rather than silently applied to a different
   * position than the player was looking at.
   */
  expectedPly?: number;
}

export type MoveRejection =
  | "illegal_history"
  | "not_your_turn"
  | "illegal_move"
  | "stale_state"
  | "malformed";

export interface MoveAccepted {
  ok: true;
  /** Official SAN, generated by the server. */
  san: string;
  /** Official FEN after the move, generated by the server. */
  fen: string;
  /** Whose turn it now is. */
  turn: "w" | "b";
  plies: number;
  termination: Termination;
  /** Winner when the move ended the game by checkmate, else null. */
  winner: "w" | "b" | null;
  isDraw: boolean;
  /** True when this move ended the game by any rule. */
  endsGame: boolean;
}

export interface MoveRejected {
  ok: false;
  reason: MoveRejection;
  detail: string;
}

export type MoveResult = MoveAccepted | MoveRejected;

const SQUARE = /^[a-h][1-8]$/;

/**
 * Validate `intent` against the authoritative `moves` history.
 *
 * `moverColor` is derived by the caller from the game row (who is host, and
 * which colour the host has) — never from anything the client sent.
 */
export function validateMove(
  moves: readonly string[],
  intent: MoveIntent,
  moverColor: "w" | "b"
): MoveResult {
  if (!intent || typeof intent.from !== "string" || typeof intent.to !== "string") {
    return { ok: false, reason: "malformed", detail: "from and to are required" };
  }
  if (!SQUARE.test(intent.from) || !SQUARE.test(intent.to)) {
    return { ok: false, reason: "malformed", detail: "from/to must be squares like e2" };
  }
  if (intent.promotion && !["q", "r", "b", "n"].includes(intent.promotion)) {
    return { ok: false, reason: "malformed", detail: "invalid promotion piece" };
  }

  // The stored history is itself checked, not assumed. If it does not replay,
  // the game is corrupt and no further move may be added to it.
  const history = verifyGame(moves);
  if (!history.legal) {
    return {
      ok: false,
      reason: "illegal_history",
      detail: `stored move ${history.illegalAtPly} does not replay`,
    };
  }

  // Optimistic concurrency. A double-click, a retry, or a second tab acting on
  // yesterday's board all land here.
  if (typeof intent.expectedPly === "number" && intent.expectedPly !== history.plies) {
    return {
      ok: false,
      reason: "stale_state",
      detail: `client expected ply ${intent.expectedPly}, game is at ${history.plies}`,
    };
  }

  // Turn is decided by the reconstructed position, not by a column a client
  // could race. This also closes the untimed-game hole, where the SQL function
  // returns before its own turn check.
  if (history.turn !== moverColor) {
    return { ok: false, reason: "not_your_turn", detail: `it is ${history.turn} to move` };
  }

  const game = new Chess();
  for (const san of moves) game.move(san);

  let made;
  try {
    made = game.move({ from: intent.from, to: intent.to, promotion: intent.promotion ?? "q" });
  } catch {
    made = null;
  }
  if (!made) {
    return { ok: false, reason: "illegal_move", detail: `${intent.from}-${intent.to} is not legal` };
  }

  // Everything below is server-generated. None of it came from the browser.
  const isCheckmate = game.isCheckmate();
  const isStalemate = game.isStalemate();
  const insufficient = game.isInsufficientMaterial();
  const threefold = game.isThreefoldRepetition();
  const otherDraw = game.isDraw();

  let termination: Termination = "ongoing";
  if (isCheckmate) termination = "checkmate";
  else if (isStalemate) termination = "stalemate";
  else if (insufficient) termination = "insufficient_material";
  else if (threefold) termination = "threefold_repetition";
  else if (otherDraw) termination = "fifty_move";

  const isDraw = termination !== "ongoing" && termination !== "checkmate";

  return {
    ok: true,
    san: made.san,
    fen: game.fen(),
    turn: game.turn() as "w" | "b",
    plies: history.plies + 1,
    termination,
    // The side that just moved delivered mate.
    winner: isCheckmate ? moverColor : null,
    isDraw,
    endsGame: termination !== "ongoing",
  };
}
