-- Phase 14B: expand the Daily Challenge candidate pool from the original
-- 24 puzzles to the full validated 1,000-puzzle library.
--
-- get_daily_challenge() (migration 0025) selects today's puzzle for a child
-- from public.daily_challenge_puzzles, a METADATA-ONLY mirror of the puzzle
-- library: puzzle_id / level / mate_in / theme -- never FEN. The client
-- already has full puzzle content (FEN + move/checkmate validation) via
-- content/puzzles.ts + lib/chess-engine/puzzleValidation.ts, unchanged.
--
-- This migration is the SAME kind of hand-kept-in-sync seed 0025 used for
-- the first 24 rows, just regenerated for all 1,000 by
-- scripts/generate-daily-challenge-seed.js from content/puzzles.ts (run
-- `node scripts/generate-daily-challenge-seed.js --check` in CI to catch
-- drift). `level` is the literal output of scripts/compute-puzzle-levels.js
-- as recorded in content/puzzles.ts; `theme` and `mate_in` are copied
-- verbatim. Rows are sorted (mate_in, level, puzzle_id).
--
-- Deliberately NOT changed by this migration:
--   * daily_challenge_history (schema, data, and its FK to
--     daily_challenge_puzzles.puzzle_id) -- every id 0025 seeded is a subset
--     of the 1,000, so all existing history rows stay valid;
--   * RLS on either table;
--   * get_daily_challenge() / record_daily_challenge_result() -- the RPC
--     logic is unchanged, it simply now has 1,000 candidates instead of 24;
--   * no new tables, no dropped rows (a plain additive upsert -- pruning
--     rows not in the library is intentionally skipped: the FK has no
--     ON DELETE clause, so deleting a puzzle_id referenced by history would
--     fail, and no such row exists to justify the risk).
--
-- Composition of the 1,000: mate-in-1 380, mate-in-2 420, mate-in-3 200;
-- level 1 210, level 2 170, level 3 375, level 4 45, level 5 192, level 6 8.

insert into public.daily_challenge_puzzles (puzzle_id, level, mate_in, theme) values
  ('lichess-01cZp', 1, 1, 'Checkmate in 1'),
  ('lichess-02LWp', 1, 1, 'Opera Mate'),
  ('lichess-02ry1', 1, 1, 'Epaulette Mate'),
  ('lichess-0Ab9p', 1, 1, 'Anastasia''s Mate'),
  ('lichess-16aDE', 1, 1, 'Checkmate in 1'),
  ('lichess-1a77x', 1, 1, 'Checkmate in 1'),
  ('lichess-1HH1g', 1, 1, 'Checkmate in 1'),
  ('lichess-25hCa', 1, 1, 'Checkmate in 1'),
  ('lichess-2DS1Z', 1, 1, 'Epaulette Mate'),
  ('lichess-2oc7h', 1, 1, 'Checkmate in 1'),
  ('lichess-2p63a', 1, 1, 'Anastasia''s Mate'),
  ('lichess-3Le8P', 1, 1, 'Checkmate in 1'),
  ('lichess-3ofF3', 1, 1, 'Checkmate in 1'),
  ('lichess-3UB9n', 1, 1, 'Checkmate in 1'),
  ('lichess-3uQO4', 1, 1, 'Double Bishop Mate'),
  ('lichess-3W5t7', 1, 1, 'Checkmate in 1'),
  ('lichess-46qrx', 1, 1, 'Checkmate in 1'),
  ('lichess-49QgJ', 1, 1, 'Checkmate in 1'),
  ('lichess-4IGrr', 1, 1, 'Checkmate in 1'),
  ('lichess-518gj', 1, 1, 'Smothered Mate'),
  ('lichess-57Xa0', 1, 1, 'Checkmate in 1'),
  ('lichess-5nVfS', 1, 1, 'Boden''s Mate'),
  ('lichess-5v4z4', 1, 1, 'Checkmate in 1'),
  ('lichess-6On3z', 1, 1, 'Checkmate in 1'),
  ('lichess-6W8vV', 1, 1, 'Checkmate in 1'),
  ('lichess-7qp2j', 1, 1, 'Back-Rank Mate'),
  ('lichess-8F8nv', 1, 1, 'Checkmate in 1'),
  ('lichess-8jmff', 1, 1, 'Arabian Mate'),
  ('lichess-8UqNY', 1, 1, 'Smothered Mate'),
  ('lichess-8vrSa', 1, 1, 'Checkmate in 1'),
  ('lichess-9nDqr', 1, 1, 'Opera Mate'),
  ('lichess-9RBZG', 1, 1, 'Double Bishop Mate'),
  ('lichess-A3cMn', 1, 1, 'Opera Mate'),
  ('lichess-a5q2g', 1, 1, 'Checkmate in 1'),
  ('lichess-aaaY1', 1, 1, 'Checkmate in 1'),
  ('lichess-ALgT0', 1, 1, 'Checkmate in 1'),
  ('lichess-AmMKW', 1, 1, 'Anastasia''s Mate'),
  ('lichess-AXah7', 1, 1, 'Checkmate in 1'),
  ('lichess-B9rY3', 1, 1, 'Checkmate in 1'),
  ('lichess-BIiJ6', 1, 1, 'Checkmate in 1'),
  ('lichess-BpSVG', 1, 1, 'Opera Mate'),
  ('lichess-ByDtP', 1, 1, 'Opera Mate'),
  ('lichess-BYPi5', 1, 1, 'Checkmate in 1'),
  ('lichess-Ceb1j', 1, 1, 'Pillsburys Mate'),
  ('lichess-CJTAB', 1, 1, 'Checkmate in 1'),
  ('lichess-CnJ5M', 1, 1, 'Opera Mate'),
  ('lichess-cpExN', 1, 1, 'Checkmate in 1'),
  ('lichess-crpMu', 1, 1, 'Smothered Mate'),
  ('lichess-cRUK8', 1, 1, 'Back-Rank Mate'),
  ('lichess-CSPNx', 1, 1, 'Double Bishop Mate'),
  ('lichess-CwXhU', 1, 1, 'Arabian Mate'),
  ('lichess-DIuFN', 1, 1, 'Checkmate in 1'),
  ('lichess-dj8Gk', 1, 1, 'Double Bishop Mate'),
  ('lichess-DkTSv', 1, 1, 'Checkmate in 1'),
  ('lichess-DkyZ5', 1, 1, 'Checkmate in 1'),
  ('lichess-dP73s', 1, 1, 'Arabian Mate'),
  ('lichess-DSNLK', 1, 1, 'Checkmate in 1'),
  ('lichess-e9AMT', 1, 1, 'Checkmate in 1'),
  ('lichess-ebxFq', 1, 1, 'Checkmate in 1'),
  ('lichess-edddW', 1, 1, 'Checkmate in 1'),
  ('lichess-eexTf', 1, 1, 'Anastasia''s Mate'),
  ('lichess-eezfL', 1, 1, 'Opera Mate'),
  ('lichess-eFQ2q', 1, 1, 'Back-Rank Mate'),
  ('lichess-eIpxd', 1, 1, 'Anastasia''s Mate'),
  ('lichess-eryP4', 1, 1, 'Checkmate in 1'),
  ('lichess-Esk1z', 1, 1, 'Checkmate in 1'),
  ('lichess-EulHd', 1, 1, 'Checkmate in 1'),
  ('lichess-F5DtV', 1, 1, 'Checkmate in 1'),
  ('lichess-f6nOA', 1, 1, 'Checkmate in 1'),
  ('lichess-FAyQ7', 1, 1, 'Hook Mate'),
  ('lichess-FBvzn', 1, 1, 'Checkmate in 1'),
  ('lichess-fcpMy', 1, 1, 'Checkmate in 1'),
  ('lichess-FGXfC', 1, 1, 'Checkmate in 1'),
  ('lichess-FI64A', 1, 1, 'Opera Mate'),
  ('lichess-FIEL8', 1, 1, 'Back-Rank Mate'),
  ('lichess-fQ7C9', 1, 1, 'Checkmate in 1'),
  ('lichess-FQ9At', 1, 1, 'Checkmate in 1'),
  ('lichess-GhNUd', 1, 1, 'Checkmate in 1'),
  ('lichess-GMLea', 1, 1, 'Anastasia''s Mate'),
  ('lichess-gN2yF', 1, 1, 'Checkmate in 1'),
  ('lichess-GW5Ow', 1, 1, 'Checkmate in 1'),
  ('lichess-GwwAo', 1, 1, 'Anastasia''s Mate'),
  ('lichess-gzK0T', 1, 1, 'Smothered Mate'),
  ('lichess-h6ISr', 1, 1, 'Checkmate in 1'),
  ('lichess-H8MG6', 1, 1, 'Arabian Mate'),
  ('lichess-hG1eB', 1, 1, 'Checkmate in 1'),
  ('lichess-hGndC', 1, 1, 'Checkmate in 1'),
  ('lichess-HkrMS', 1, 1, 'Checkmate in 1'),
  ('lichess-Hl8Mg', 1, 1, 'Checkmate in 1'),
  ('lichess-HntIa', 1, 1, 'Anastasia''s Mate'),
  ('lichess-hrgI3', 1, 1, 'Checkmate in 1'),
  ('lichess-HVvBD', 1, 1, 'Checkmate in 1'),
  ('lichess-hwHaX', 1, 1, 'Arabian Mate'),
  ('lichess-HxhDj', 1, 1, 'Double Bishop Mate'),
  ('lichess-HY9Mz', 1, 1, 'Checkmate in 1'),
  ('lichess-IAqqY', 1, 1, 'Checkmate in 1'),
  ('lichess-Idri0', 1, 1, 'Checkmate in 1'),
  ('lichess-ie741', 1, 1, 'Boden''s Mate'),
  ('lichess-iKhD0', 1, 1, 'Hook Mate'),
  ('lichess-iszc0', 1, 1, 'Checkmate in 1'),
  ('lichess-izu8A', 1, 1, 'Checkmate in 1'),
  ('lichess-J3mpb', 1, 1, 'Pillsburys Mate'),
  ('lichess-JPBQl', 1, 1, 'Checkmate in 1'),
  ('lichess-JTeiN', 1, 1, 'Pillsburys Mate'),
  ('lichess-k6B8z', 1, 1, 'Checkmate in 1'),
  ('lichess-K8bar', 1, 1, 'Boden''s Mate'),
  ('lichess-ki6dK', 1, 1, 'Anastasia''s Mate'),
  ('lichess-kKFiE', 1, 1, 'Corner Mate'),
  ('lichess-kU1se', 1, 1, 'Back-Rank Mate'),
  ('lichess-LdneV', 1, 1, 'Checkmate in 1'),
  ('lichess-LeZuJ', 1, 1, 'Opera Mate'),
  ('lichess-lTjeE', 1, 1, 'Checkmate in 1'),
  ('lichess-LUDef', 1, 1, 'Corner Mate'),
  ('lichess-LXgya', 1, 1, 'Checkmate in 1'),
  ('lichess-LXPJc', 1, 1, 'Checkmate in 1'),
  ('lichess-lyS9L', 1, 1, 'Smothered Mate'),
  ('lichess-MtDEZ', 1, 1, 'Anastasia''s Mate'),
  ('lichess-mV0ie', 1, 1, 'Anastasia''s Mate'),
  ('lichess-N97dT', 1, 1, 'Anastasia''s Mate'),
  ('lichess-NfUfv', 1, 1, 'Pillsburys Mate'),
  ('lichess-NiwVT', 1, 1, 'Epaulette Mate'),
  ('lichess-NRnMZ', 1, 1, 'Checkmate in 1'),
  ('lichess-nShqm', 1, 1, 'Checkmate in 1'),
  ('lichess-nVGv8', 1, 1, 'Checkmate in 1'),
  ('lichess-O4R3J', 1, 1, 'Double Bishop Mate'),
  ('lichess-OekUd', 1, 1, 'Checkmate in 1'),
  ('lichess-oSKvp', 1, 1, 'Epaulette Mate'),
  ('lichess-OvCxj', 1, 1, 'Opera Mate'),
  ('lichess-p5ob2', 1, 1, 'Checkmate in 1'),
  ('lichess-PpICs', 1, 1, 'Checkmate in 1'),
  ('lichess-PVnNv', 1, 1, 'Epaulette Mate'),
  ('lichess-Q8PSa', 1, 1, 'Checkmate in 1'),
  ('lichess-qBZKv', 1, 1, 'Opera Mate'),
  ('lichess-QFEOD', 1, 1, 'Checkmate in 1'),
  ('lichess-QjvoC', 1, 1, 'Epaulette Mate'),
  ('lichess-Qkqbg', 1, 1, 'Opera Mate'),
  ('lichess-qmDpB', 1, 1, 'Checkmate in 1'),
  ('lichess-qmt54', 1, 1, 'Smothered Mate'),
  ('lichess-QnyuT', 1, 1, 'Anastasia''s Mate'),
  ('lichess-qUyts', 1, 1, 'Checkmate in 1'),
  ('lichess-QzEIx', 1, 1, 'Hook Mate'),
  ('lichess-QZiq0', 1, 1, 'Checkmate in 1'),
  ('lichess-rpKpD', 1, 1, 'Checkmate in 1'),
  ('lichess-RRD3q', 1, 1, 'Checkmate in 1'),
  ('lichess-rvPlk', 1, 1, 'Smothered Mate'),
  ('lichess-RYBZB', 1, 1, 'Arabian Mate'),
  ('lichess-rzYAg', 1, 1, 'Checkmate in 1'),
  ('lichess-Sd8uu', 1, 1, 'Checkmate in 1'),
  ('lichess-sEnzj', 1, 1, 'Opera Mate'),
  ('lichess-siqhI', 1, 1, 'Checkmate in 1'),
  ('lichess-sK2pe', 1, 1, 'Checkmate in 1'),
  ('lichess-t5TgX', 1, 1, 'Pillsburys Mate'),
  ('lichess-T75np', 1, 1, 'Checkmate in 1'),
  ('lichess-TBUvz', 1, 1, 'Checkmate in 1'),
  ('lichess-tGkLe', 1, 1, 'Checkmate in 1'),
  ('lichess-Tgn2P', 1, 1, 'Checkmate in 1'),
  ('lichess-tQhxY', 1, 1, 'Anastasia''s Mate'),
  ('lichess-TXTVc', 1, 1, 'Smothered Mate'),
  ('lichess-u4b8Y', 1, 1, 'Epaulette Mate'),
  ('lichess-U8MXf', 1, 1, 'Arabian Mate'),
  ('lichess-U97G4', 1, 1, 'Checkmate in 1'),
  ('lichess-UB9zi', 1, 1, 'Checkmate in 1'),
  ('lichess-uri2r', 1, 1, 'Checkmate in 1'),
  ('lichess-UrtUC', 1, 1, 'Anastasia''s Mate'),
  ('lichess-USiA6', 1, 1, 'Smothered Mate'),
  ('lichess-UsJmu', 1, 1, 'Checkmate in 1'),
  ('lichess-Ut660', 1, 1, 'Smothered Mate'),
  ('lichess-UvAsu', 1, 1, 'Checkmate in 1'),
  ('lichess-UYf00', 1, 1, 'Corner Mate'),
  ('lichess-v30I6', 1, 1, 'Arabian Mate'),
  ('lichess-v8PEU', 1, 1, 'Checkmate in 1'),
  ('lichess-vd4i2', 1, 1, 'Checkmate in 1'),
  ('lichess-vjLPX', 1, 1, 'Pillsburys Mate'),
  ('lichess-vT1yc', 1, 1, 'Checkmate in 1'),
  ('lichess-VTHFy', 1, 1, 'Checkmate in 1'),
  ('lichess-vtIqw', 1, 1, 'Opera Mate'),
  ('lichess-VyRBJ', 1, 1, 'Opera Mate'),
  ('lichess-WDwkh', 1, 1, 'Checkmate in 1'),
  ('lichess-wH7Uo', 1, 1, 'Checkmate in 1'),
  ('lichess-WWuBW', 1, 1, 'Checkmate in 1'),
  ('lichess-XcQ7z', 1, 1, 'Corner Mate'),
  ('lichess-xhlVo', 1, 1, 'Checkmate in 1'),
  ('lichess-xICM0', 1, 1, 'Double Bishop Mate'),
  ('lichess-XmDuX', 1, 1, 'Checkmate in 1'),
  ('lichess-XQIin', 1, 1, 'Checkmate in 1'),
  ('lichess-XqXRe', 1, 1, 'Checkmate in 1'),
  ('lichess-XUkYa', 1, 1, 'Arabian Mate'),
  ('lichess-xy4M4', 1, 1, 'Checkmate in 1'),
  ('lichess-ykBUd', 1, 1, 'Vukovic Mate'),
  ('lichess-YQLCN', 1, 1, 'Checkmate in 1'),
  ('lichess-z7VN3', 1, 1, 'Opera Mate'),
  ('lichess-Z8sMS', 1, 1, 'Arabian Mate'),
  ('lichess-zJcOW', 1, 1, 'Checkmate in 1'),
  ('lichess-ZQnwo', 1, 1, 'Anastasia''s Mate'),
  ('lichess-ZXhp9', 1, 1, 'Pillsburys Mate'),
  ('lichess-zz3kt', 1, 1, 'Double Bishop Mate'),
  ('lichess-zzodd', 1, 1, 'Pillsburys Mate'),
  ('m1-backrank-bishop-guard', 1, 1, 'Back-Rank Mate'),
  ('m1-backrank-queen', 1, 1, 'Back-Rank Mate'),
  ('m1-backrank-rook', 1, 1, 'Back-Rank Mate'),
  ('m1-backrank-sealed', 1, 1, 'Back-Rank Mate'),
  ('m1-corner-queen-a', 1, 1, 'Cornered King'),
  ('m1-corner-queen-b', 1, 1, 'Cornered King'),
  ('m1-epaulette-mate', 1, 1, 'Epaulette Mate'),
  ('m1-king-rook-ladder', 1, 1, 'King & Rook Mate'),
  ('m1-ladder-mid-a', 1, 1, 'Rook Ladder'),
  ('m1-opera-mate', 1, 1, 'Opera Mate'),
  ('m1-pawn-break-mate', 1, 1, 'Pawn Mate'),
  ('m1-smothered-corner', 1, 1, 'Smothered Mate'),
  ('m1-smothered-knight', 1, 1, 'Smothered Mate'),
  ('lichess-0HqjA', 2, 1, 'Corner Mate'),
  ('lichess-0OCKV', 2, 1, 'Checkmate in 1'),
  ('lichess-1iXjI', 2, 1, 'Dovetail Mate'),
  ('lichess-36SAi', 2, 1, 'Checkmate in 1'),
  ('lichess-3f4YN', 2, 1, 'Checkmate in 1'),
  ('lichess-3X6Am', 2, 1, 'Checkmate in 1'),
  ('lichess-3YOPI', 2, 1, 'Checkmate in 1'),
  ('lichess-4GPXy', 2, 1, 'Checkmate in 1'),
  ('lichess-4Jrdh', 2, 1, 'Corner Mate'),
  ('lichess-5DmYI', 2, 1, 'Checkmate in 1'),
  ('lichess-6bGWq', 2, 1, 'Checkmate in 1'),
  ('lichess-6DhfY', 2, 1, 'Swallowstail Mate'),
  ('lichess-6FuIo', 2, 1, 'Checkmate in 1'),
  ('lichess-6r4vG', 2, 1, 'Dovetail Mate'),
  ('lichess-6XYzA', 2, 1, 'Checkmate in 1'),
  ('lichess-7AmW0', 2, 1, 'Dovetail Mate'),
  ('lichess-8C8BM', 2, 1, 'Checkmate in 1'),
  ('lichess-8jNoB', 2, 1, 'Checkmate in 1'),
  ('lichess-8NCE9', 2, 1, 'Checkmate in 1'),
  ('lichess-8uIqs', 2, 1, 'Checkmate in 1'),
  ('lichess-9i2CQ', 2, 1, 'Hook Mate'),
  ('lichess-9kzCo', 2, 1, 'Epaulette Mate'),
  ('lichess-9PC65', 2, 1, 'Checkmate in 1'),
  ('lichess-A0RkZ', 2, 1, 'Checkmate in 1'),
  ('lichess-a9R7N', 2, 1, 'Blind Swine Mate'),
  ('lichess-aha8f', 2, 1, 'Checkmate in 1'),
  ('lichess-aoYRo', 2, 1, 'Checkmate in 1'),
  ('lichess-aVKck', 2, 1, 'Dovetail Mate'),
  ('lichess-AVvT3', 2, 1, 'Checkmate in 1'),
  ('lichess-b81pW', 2, 1, 'Vukovic Mate'),
  ('lichess-BAgrJ', 2, 1, 'Checkmate in 1'),
  ('lichess-C89hb', 2, 1, 'Swallowstail Mate'),
  ('lichess-cILWf', 2, 1, 'Checkmate in 1'),
  ('lichess-CIxaX', 2, 1, 'Checkmate in 1'),
  ('lichess-ck14E', 2, 1, 'Epaulette Mate'),
  ('lichess-CQnX6', 2, 1, 'Blind Swine Mate'),
  ('lichess-CTH2w', 2, 1, 'Checkmate in 1'),
  ('lichess-cVfKc', 2, 1, 'Checkmate in 1'),
  ('lichess-dapUB', 2, 1, 'Checkmate in 1'),
  ('lichess-dfmgh', 2, 1, 'Checkmate in 1'),
  ('lichess-DoqKD', 2, 1, 'Checkmate in 1'),
  ('lichess-Dsetz', 2, 1, 'Checkmate in 1'),
  ('lichess-dvYty', 2, 1, 'Swallowstail Mate'),
  ('lichess-DWJVC', 2, 1, 'Checkmate in 1'),
  ('lichess-E4pQL', 2, 1, 'Checkmate in 1'),
  ('lichess-eazHt', 2, 1, 'Checkmate in 1'),
  ('lichess-eEAvx', 2, 1, 'Hook Mate'),
  ('lichess-EkHOm', 2, 1, 'Hook Mate'),
  ('lichess-EMc7o', 2, 1, 'Checkmate in 1'),
  ('lichess-ETYnM', 2, 1, 'Checkmate in 1'),
  ('lichess-EYfDt', 2, 1, 'Pillsburys Mate'),
  ('lichess-f1HNz', 2, 1, 'Checkmate in 1'),
  ('lichess-fBxWw', 2, 1, 'Checkmate in 1'),
  ('lichess-fDDgS', 2, 1, 'Checkmate in 1'),
  ('lichess-fgy35', 2, 1, 'Checkmate in 1'),
  ('lichess-FJAa9', 2, 1, 'Checkmate in 1'),
  ('lichess-fnc8k', 2, 1, 'Checkmate in 1'),
  ('lichess-FPIa6', 2, 1, 'Hook Mate'),
  ('lichess-FqELM', 2, 1, 'Checkmate in 1'),
  ('lichess-FSZ6e', 2, 1, 'Checkmate in 1'),
  ('lichess-FXH2g', 2, 1, 'Dovetail Mate'),
  ('lichess-g03N8', 2, 1, 'Blind Swine Mate'),
  ('lichess-G4lo8', 2, 1, 'Checkmate in 1'),
  ('lichess-g62gb', 2, 1, 'Checkmate in 1'),
  ('lichess-gdpuJ', 2, 1, 'Hook Mate'),
  ('lichess-GoWhy', 2, 1, 'Kill Box Mate'),
  ('lichess-gxZ94', 2, 1, 'Corner Mate'),
  ('lichess-Gybzt', 2, 1, 'Checkmate in 1'),
  ('lichess-gyMQc', 2, 1, 'Dovetail Mate'),
  ('lichess-H3Ptl', 2, 1, 'Dovetail Mate'),
  ('lichess-Hk71o', 2, 1, 'Dovetail Mate'),
  ('lichess-hpxZ5', 2, 1, 'Checkmate in 1'),
  ('lichess-hQoAw', 2, 1, 'Checkmate in 1'),
  ('lichess-HRTN1', 2, 1, 'Dovetail Mate'),
  ('lichess-htJ1N', 2, 1, 'Checkmate in 1'),
  ('lichess-hXQDB', 2, 1, 'Pillsburys Mate'),
  ('lichess-I2Jp8', 2, 1, 'Checkmate in 1'),
  ('lichess-IDrhf', 2, 1, 'Swallowstail Mate'),
  ('lichess-IXatz', 2, 1, 'Checkmate in 1'),
  ('lichess-j5Vq3', 2, 1, 'Checkmate in 1'),
  ('lichess-jEorh', 2, 1, 'Corner Mate'),
  ('lichess-jFeIm', 2, 1, 'Opera Mate'),
  ('lichess-jIPIo', 2, 1, 'Checkmate in 1'),
  ('lichess-jPZD2', 2, 1, 'Checkmate in 1'),
  ('lichess-k9Ksy', 2, 1, 'Checkmate in 1'),
  ('lichess-kaqLu', 2, 1, 'Checkmate in 1'),
  ('lichess-kASeE', 2, 1, 'Corner Mate'),
  ('lichess-kEE6s', 2, 1, 'Checkmate in 1'),
  ('lichess-kFGpg', 2, 1, 'Checkmate in 1'),
  ('lichess-kpDy0', 2, 1, 'Checkmate in 1'),
  ('lichess-l0ChA', 2, 1, 'Checkmate in 1'),
  ('lichess-l147N', 2, 1, 'Checkmate in 1'),
  ('lichess-lhLZT', 2, 1, 'Checkmate in 1'),
  ('lichess-LIGYq', 2, 1, 'Corner Mate'),
  ('lichess-LjUjZ', 2, 1, 'Triangle Mate'),
  ('lichess-lnF1r', 2, 1, 'Checkmate in 1'),
  ('lichess-M4Nnp', 2, 1, 'Corner Mate'),
  ('lichess-m6cAR', 2, 1, 'Checkmate in 1'),
  ('lichess-MqkRd', 2, 1, 'Checkmate in 1'),
  ('lichess-MSwZf', 2, 1, 'Checkmate in 1'),
  ('lichess-mtWBu', 2, 1, 'Checkmate in 1'),
  ('lichess-MvjGR', 2, 1, 'Checkmate in 1'),
  ('lichess-N1FYo', 2, 1, 'Dovetail Mate'),
  ('lichess-nMzYW', 2, 1, 'Checkmate in 1'),
  ('lichess-NNzh1', 2, 1, 'Checkmate in 1'),
  ('lichess-nzDGG', 2, 1, 'Hook Mate'),
  ('lichess-O4ESz', 2, 1, 'Checkmate in 1'),
  ('lichess-ocK7S', 2, 1, 'Checkmate in 1'),
  ('lichess-oeKkj', 2, 1, 'Kill Box Mate'),
  ('lichess-OgvDL', 2, 1, 'Dovetail Mate'),
  ('lichess-oJrFT', 2, 1, 'Checkmate in 1'),
  ('lichess-OurgW', 2, 1, 'Dovetail Mate'),
  ('lichess-pbURu', 2, 1, 'Checkmate in 1'),
  ('lichess-pbxSm', 2, 1, 'Checkmate in 1'),
  ('lichess-Pj2jb', 2, 1, 'Blind Swine Mate'),
  ('lichess-pqmZ4', 2, 1, 'Dovetail Mate'),
  ('lichess-q07Qx', 2, 1, 'Checkmate in 1'),
  ('lichess-Q2Gdb', 2, 1, 'Checkmate in 1'),
  ('lichess-QaW24', 2, 1, 'Epaulette Mate'),
  ('lichess-qTd3f', 2, 1, 'Checkmate in 1'),
  ('lichess-RaSeU', 2, 1, 'Checkmate in 1'),
  ('lichess-RMHad', 2, 1, 'Checkmate in 1'),
  ('lichess-rMxg6', 2, 1, 'Checkmate in 1'),
  ('lichess-Rp6W7', 2, 1, 'Checkmate in 1'),
  ('lichess-RphMw', 2, 1, 'Checkmate in 1'),
  ('lichess-s0wxK', 2, 1, 'Checkmate in 1'),
  ('lichess-S8yd5', 2, 1, 'Dovetail Mate'),
  ('lichess-sAORO', 2, 1, 'Checkmate in 1'),
  ('lichess-sbU5w', 2, 1, 'Checkmate in 1'),
  ('lichess-sh2dc', 2, 1, 'Checkmate in 1'),
  ('lichess-sO3My', 2, 1, 'Dovetail Mate'),
  ('lichess-SpNGT', 2, 1, 'Blind Swine Mate'),
  ('lichess-srZpg', 2, 1, 'Pillsburys Mate'),
  ('lichess-t1Boe', 2, 1, 'Back-Rank Mate'),
  ('lichess-Ta5E6', 2, 1, 'Kill Box Mate'),
  ('lichess-TFKPs', 2, 1, 'Checkmate in 1'),
  ('lichess-TlsXU', 2, 1, 'Pillsburys Mate'),
  ('lichess-tNTTR', 2, 1, 'Checkmate in 1'),
  ('lichess-trTUL', 2, 1, 'Checkmate in 1'),
  ('lichess-TsJtj', 2, 1, 'Hook Mate'),
  ('lichess-TT5SV', 2, 1, 'Checkmate in 1'),
  ('lichess-tvKb4', 2, 1, 'Checkmate in 1'),
  ('lichess-TzdYJ', 2, 1, 'Checkmate in 1'),
  ('lichess-uZJcq', 2, 1, 'Checkmate in 1'),
  ('lichess-v2PW7', 2, 1, 'Checkmate in 1'),
  ('lichess-v2U2Z', 2, 1, 'Dovetail Mate'),
  ('lichess-v32iD', 2, 1, 'Checkmate in 1'),
  ('lichess-VCC56', 2, 1, 'Checkmate in 1'),
  ('lichess-vDC0y', 2, 1, 'Checkmate in 1'),
  ('lichess-vSwTb', 2, 1, 'Back-Rank Mate'),
  ('lichess-vuSm4', 2, 1, 'Checkmate in 1'),
  ('lichess-W8axp', 2, 1, 'Checkmate in 1'),
  ('lichess-WoIfN', 2, 1, 'Opera Mate'),
  ('lichess-Wvzht', 2, 1, 'Checkmate in 1'),
  ('lichess-x8e0v', 2, 1, 'Pillsburys Mate'),
  ('lichess-xBg7g', 2, 1, 'Checkmate in 1'),
  ('lichess-XV4ob', 2, 1, 'Checkmate in 1'),
  ('lichess-xvQ7J', 2, 1, 'Checkmate in 1'),
  ('lichess-Xwmbg', 2, 1, 'Checkmate in 1'),
  ('lichess-Yg0Fk', 2, 1, 'Checkmate in 1'),
  ('lichess-yGzup', 2, 1, 'Checkmate in 1'),
  ('lichess-yNbHt', 2, 1, 'Checkmate in 1'),
  ('lichess-yzkfn', 2, 1, 'Checkmate in 1'),
  ('lichess-z5yMb', 2, 1, 'Checkmate in 1'),
  ('lichess-Zs903', 2, 1, 'Blind Swine Mate'),
  ('m1-corner-rook-a', 2, 1, 'Corridor Mate'),
  ('m1-corner-rook-b', 2, 1, 'Corridor Mate'),
  ('m1-knight-rook-a', 2, 1, 'Knight & Rook Mate'),
  ('m1-queen-bishop-g2', 2, 1, 'Queen & Bishop Mate'),
  ('m1-two-rooks-adjacent', 2, 1, 'Rook Ladder'),
  ('lichess-06xEN', 3, 2, 'Checkmate in 2'),
  ('lichess-0crO9', 3, 2, 'Arabian Mate'),
  ('lichess-0DK93', 3, 2, 'Vukovic Mate'),
  ('lichess-0GhM8', 3, 2, 'Dovetail Mate'),
  ('lichess-0KhAG', 3, 2, 'Checkmate in 2'),
  ('lichess-0NVIr', 3, 2, 'Smothered Mate'),
  ('lichess-0OIxJ', 3, 2, 'Checkmate in 2'),
  ('lichess-0OY0a', 3, 2, 'Opera Mate'),
  ('lichess-0UI0C', 3, 2, 'Checkmate in 2'),
  ('lichess-0uU9p', 3, 2, 'Back-Rank Mate'),
  ('lichess-0z923', 3, 2, 'Checkmate in 2'),
  ('lichess-1KmUC', 3, 2, 'Pillsburys Mate'),
  ('lichess-1nQOt', 3, 2, 'Vukovic Mate'),
  ('lichess-1P7pY', 3, 2, 'Double Bishop Mate'),
  ('lichess-1reTT', 3, 2, 'Checkmate in 2'),
  ('lichess-1RlN1', 3, 2, 'Checkmate in 2'),
  ('lichess-1tc4Q', 3, 2, 'Pillsburys Mate'),
  ('lichess-2fzFJ', 3, 2, 'Opera Mate'),
  ('lichess-33JYv', 3, 2, 'Checkmate in 2'),
  ('lichess-37xoI', 3, 2, 'Checkmate in 2'),
  ('lichess-3d9g6', 3, 2, 'Checkmate in 2'),
  ('lichess-3HnG1', 3, 2, 'Hook Mate'),
  ('lichess-3Iizu', 3, 2, 'Checkmate in 2'),
  ('lichess-3LpLf', 3, 2, 'Checkmate in 2'),
  ('lichess-3vKvW', 3, 2, 'Checkmate in 2'),
  ('lichess-4fPIa', 3, 2, 'Checkmate in 2'),
  ('lichess-4k4y2', 3, 2, 'Anastasia''s Mate'),
  ('lichess-4QLzW', 3, 2, 'Checkmate in 2'),
  ('lichess-4rgB5', 3, 2, 'Checkmate in 2'),
  ('lichess-4SqSq', 3, 2, 'Checkmate in 2'),
  ('lichess-4v5xg', 3, 2, 'Checkmate in 2'),
  ('lichess-4wJfE', 3, 2, 'Smothered Mate'),
  ('lichess-4Xlh9', 3, 2, 'Checkmate in 2'),
  ('lichess-5d9CQ', 3, 2, 'Back-Rank Mate'),
  ('lichess-5EeT3', 3, 2, 'Checkmate in 2'),
  ('lichess-5kKU5', 3, 2, 'Smothered Mate'),
  ('lichess-5LzxV', 3, 2, 'Checkmate in 2'),
  ('lichess-5p8GI', 3, 2, 'Checkmate in 2'),
  ('lichess-5QNIs', 3, 2, 'Arabian Mate'),
  ('lichess-5RDrC', 3, 2, 'Pillsburys Mate'),
  ('lichess-5SuQG', 3, 2, 'Corner Mate'),
  ('lichess-5TALP', 3, 2, 'Back-Rank Mate'),
  ('lichess-60F8m', 3, 2, 'Anastasia''s Mate'),
  ('lichess-6hvxj', 3, 2, 'Checkmate in 2'),
  ('lichess-6iHgR', 3, 2, 'Checkmate in 2'),
  ('lichess-6m0ya', 3, 2, 'Checkmate in 2'),
  ('lichess-6MmKt', 3, 2, 'Checkmate in 2'),
  ('lichess-6qxId', 3, 2, 'Back-Rank Mate'),
  ('lichess-6RmWD', 3, 2, 'Checkmate in 2'),
  ('lichess-6Thy3', 3, 2, 'Checkmate in 2'),
  ('lichess-6w0le', 3, 2, 'Double Bishop Mate'),
  ('lichess-6wJye', 3, 2, 'Checkmate in 2'),
  ('lichess-73mRs', 3, 2, 'Checkmate in 2'),
  ('lichess-7Abku', 3, 2, 'Checkmate in 2'),
  ('lichess-7aWky', 3, 2, 'Double Bishop Mate'),
  ('lichess-7Q5OB', 3, 2, 'Checkmate in 2'),
  ('lichess-7qCSf', 3, 2, 'Smothered Mate'),
  ('lichess-7sVCg', 3, 2, 'Checkmate in 2'),
  ('lichess-7YU0L', 3, 2, 'Checkmate in 2'),
  ('lichess-7ZphA', 3, 2, 'Checkmate in 2'),
  ('lichess-85MrZ', 3, 2, 'Smothered Mate'),
  ('lichess-8AvGo', 3, 2, 'Anastasia''s Mate'),
  ('lichess-8CpTD', 3, 2, 'Back-Rank Mate'),
  ('lichess-8dyGV', 3, 2, 'Pillsburys Mate'),
  ('lichess-8fszV', 3, 2, 'Checkmate in 2'),
  ('lichess-8hNqc', 3, 2, 'Checkmate in 2'),
  ('lichess-8NKQx', 3, 2, 'Smothered Mate'),
  ('lichess-8onPD', 3, 2, 'Checkmate in 2'),
  ('lichess-8p4Sg', 3, 2, 'Checkmate in 2'),
  ('lichess-8Sjz6', 3, 2, 'Opera Mate'),
  ('lichess-90Wbk', 3, 2, 'Opera Mate'),
  ('lichess-919jn', 3, 2, 'Checkmate in 2'),
  ('lichess-9cxhl', 3, 2, 'Arabian Mate'),
  ('lichess-9GVGf', 3, 2, 'Checkmate in 2'),
  ('lichess-9Hl5V', 3, 2, 'Checkmate in 2'),
  ('lichess-9mDmj', 3, 2, 'Checkmate in 2'),
  ('lichess-9Nodo', 3, 2, 'Vukovic Mate'),
  ('lichess-9ySYx', 3, 2, 'Checkmate in 2'),
  ('lichess-A04Ld', 3, 2, 'Back-Rank Mate'),
  ('lichess-a0N0p', 3, 2, 'Checkmate in 2'),
  ('lichess-A1I3D', 3, 2, 'Kill Box Mate'),
  ('lichess-A1y74', 3, 2, 'Corner Mate'),
  ('lichess-A3HnH', 3, 2, 'Pillsburys Mate'),
  ('lichess-acmL9', 3, 2, 'Checkmate in 2'),
  ('lichess-Ahm2m', 3, 2, 'Checkmate in 2'),
  ('lichess-aLaRV', 3, 2, 'Checkmate in 2'),
  ('lichess-AnC00', 3, 2, 'Checkmate in 2'),
  ('lichess-ANmgX', 3, 2, 'Checkmate in 2'),
  ('lichess-aRJCy', 3, 2, 'Checkmate in 2'),
  ('lichess-ATkZZ', 3, 2, 'Checkmate in 2'),
  ('lichess-AvaTX', 3, 2, 'Checkmate in 2'),
  ('lichess-awdWd', 3, 2, 'Hook Mate'),
  ('lichess-awg9p', 3, 2, 'Checkmate in 2'),
  ('lichess-b0LNe', 3, 2, 'Checkmate in 2'),
  ('lichess-B5FPn', 3, 2, 'Double Bishop Mate'),
  ('lichess-b6JPW', 3, 2, 'Checkmate in 2'),
  ('lichess-B7iNf', 3, 2, 'Checkmate in 2'),
  ('lichess-BeWrY', 3, 2, 'Opera Mate'),
  ('lichess-bgNPx', 3, 2, 'Checkmate in 2'),
  ('lichess-bGx44', 3, 2, 'Pillsburys Mate'),
  ('lichess-BHLxJ', 3, 2, 'Hook Mate'),
  ('lichess-BnKdx', 3, 2, 'Hook Mate'),
  ('lichess-but8C', 3, 2, 'Arabian Mate'),
  ('lichess-BwddJ', 3, 2, 'Back-Rank Mate'),
  ('lichess-bZ7ik', 3, 2, 'Checkmate in 2'),
  ('lichess-BZGrJ', 3, 2, 'Checkmate in 2'),
  ('lichess-C5Va3', 3, 2, 'Opera Mate'),
  ('lichess-cDi4l', 3, 2, 'Checkmate in 2'),
  ('lichess-cG2Fz', 3, 2, 'Checkmate in 2'),
  ('lichess-CJY99', 3, 2, 'Back-Rank Mate'),
  ('lichess-csDXN', 3, 2, 'Checkmate in 2'),
  ('lichess-cwhUs', 3, 2, 'Checkmate in 2'),
  ('lichess-D4GZH', 3, 2, 'Checkmate in 2'),
  ('lichess-dH7oI', 3, 2, 'Checkmate in 2'),
  ('lichess-Dkuz7', 3, 2, 'Corner Mate'),
  ('lichess-Dkyo5', 3, 2, 'Epaulette Mate'),
  ('lichess-dm5rA', 3, 2, 'Checkmate in 2'),
  ('lichess-DOl0N', 3, 2, 'Pillsburys Mate'),
  ('lichess-dQWIo', 3, 2, 'Checkmate in 2'),
  ('lichess-dRRhp', 3, 2, 'Checkmate in 2'),
  ('lichess-DVTMz', 3, 2, 'Kill Box Mate'),
  ('lichess-dZMl0', 3, 2, 'Smothered Mate'),
  ('lichess-e8DZ2', 3, 2, 'Checkmate in 2'),
  ('lichess-ebA9K', 3, 2, 'Anastasia''s Mate'),
  ('lichess-egGM2', 3, 2, 'Checkmate in 2'),
  ('lichess-egNux', 3, 2, 'Checkmate in 2'),
  ('lichess-Ei3Kc', 3, 2, 'Checkmate in 2'),
  ('lichess-eJpmo', 3, 2, 'Pillsburys Mate'),
  ('lichess-emm8e', 3, 2, 'Checkmate in 2'),
  ('lichess-EMNy2', 3, 2, 'Vukovic Mate'),
  ('lichess-eVA32', 3, 2, 'Double Bishop Mate'),
  ('lichess-evt5N', 3, 2, 'Pillsburys Mate'),
  ('lichess-Ewipi', 3, 2, 'Arabian Mate'),
  ('lichess-eXDFv', 3, 2, 'Back-Rank Mate'),
  ('lichess-f0aa6', 3, 2, 'Checkmate in 2'),
  ('lichess-F1Dgu', 3, 2, 'Back-Rank Mate'),
  ('lichess-F1EFm', 3, 2, 'Checkmate in 2'),
  ('lichess-f89vC', 3, 2, 'Arabian Mate'),
  ('lichess-f9JIj', 3, 2, 'Checkmate in 2'),
  ('lichess-fahcM', 3, 2, 'Checkmate in 2'),
  ('lichess-FAHoF', 3, 2, 'Anastasia''s Mate'),
  ('lichess-fICSQ', 3, 2, 'Checkmate in 2'),
  ('lichess-Flq07', 3, 2, 'Checkmate in 2'),
  ('lichess-fMW0g', 3, 2, 'Checkmate in 2'),
  ('lichess-fq0Rz', 3, 2, 'Vukovic Mate'),
  ('lichess-FrHgi', 3, 2, 'Checkmate in 2'),
  ('lichess-FtfJM', 3, 2, 'Checkmate in 2'),
  ('lichess-FvGkq', 3, 2, 'Checkmate in 2'),
  ('lichess-FYRYR', 3, 2, 'Double Bishop Mate'),
  ('lichess-fz2Jf', 3, 2, 'Checkmate in 2'),
  ('lichess-G0NHh', 3, 2, 'Checkmate in 2'),
  ('lichess-GgPPP', 3, 2, 'Checkmate in 2'),
  ('lichess-GHBjm', 3, 2, 'Checkmate in 2'),
  ('lichess-GKFWQ', 3, 2, 'Pillsburys Mate'),
  ('lichess-gPSjD', 3, 2, 'Pillsburys Mate'),
  ('lichess-gTxI0', 3, 2, 'Opera Mate'),
  ('lichess-gZXlJ', 3, 2, 'Checkmate in 2'),
  ('lichess-h3pac', 3, 2, 'Double Bishop Mate'),
  ('lichess-H7Ai7', 3, 2, 'Anastasia''s Mate'),
  ('lichess-H7pzb', 3, 2, 'Checkmate in 2'),
  ('lichess-haq50', 3, 2, 'Smothered Mate'),
  ('lichess-HGCt7', 3, 2, 'Checkmate in 2'),
  ('lichess-HhuoP', 3, 2, 'Checkmate in 2'),
  ('lichess-hJiVC', 3, 2, 'Opera Mate'),
  ('lichess-HMpZJ', 3, 2, 'Checkmate in 2'),
  ('lichess-HnRUQ', 3, 2, 'Epaulette Mate'),
  ('lichess-hUpCX', 3, 2, 'Checkmate in 2'),
  ('lichess-iblq4', 3, 2, 'Checkmate in 2'),
  ('lichess-Id3BV', 3, 2, 'Checkmate in 2'),
  ('lichess-iQ6oL', 3, 2, 'Checkmate in 2'),
  ('lichess-J9CvA', 3, 2, 'Back-Rank Mate'),
  ('lichess-JDEpK', 3, 2, 'Pillsburys Mate'),
  ('lichess-jFGFm', 3, 2, 'Checkmate in 2'),
  ('lichess-JFOVI', 3, 2, 'Hook Mate'),
  ('lichess-JicAl', 3, 2, 'Checkmate in 2'),
  ('lichess-jKvR6', 3, 2, 'Double Bishop Mate'),
  ('lichess-JlaFl', 3, 2, 'Checkmate in 2'),
  ('lichess-jN2KP', 3, 2, 'Anastasia''s Mate'),
  ('lichess-jrbvX', 3, 2, 'Anastasia''s Mate'),
  ('lichess-jTCjT', 3, 2, 'Double Bishop Mate'),
  ('lichess-JtlZj', 3, 2, 'Checkmate in 2'),
  ('lichess-jwStd', 3, 2, 'Checkmate in 2'),
  ('lichess-jygK2', 3, 2, 'Checkmate in 2'),
  ('lichess-jyjKD', 3, 2, 'Checkmate in 2'),
  ('lichess-K8ZyA', 3, 2, 'Checkmate in 2'),
  ('lichess-k9lMQ', 3, 2, 'Checkmate in 2'),
  ('lichess-KcO5s', 3, 2, 'Back-Rank Mate'),
  ('lichess-kOSm3', 3, 2, 'Checkmate in 2'),
  ('lichess-kSE8N', 3, 2, 'Checkmate in 2'),
  ('lichess-KW1gz', 3, 2, 'Pillsburys Mate'),
  ('lichess-KyA4Y', 3, 2, 'Checkmate in 2'),
  ('lichess-L4p3s', 3, 2, 'Checkmate in 2'),
  ('lichess-l8FN0', 3, 2, 'Dovetail Mate'),
  ('lichess-lElbf', 3, 2, 'Checkmate in 2'),
  ('lichess-LF8L9', 3, 2, 'Pillsburys Mate'),
  ('lichess-LflW2', 3, 2, 'Arabian Mate'),
  ('lichess-LGqeF', 3, 2, 'Opera Mate'),
  ('lichess-Liudi', 3, 2, 'Pillsburys Mate'),
  ('lichess-LJPVi', 3, 2, 'Checkmate in 2'),
  ('lichess-LmR2K', 3, 2, 'Checkmate in 2'),
  ('lichess-LNdYW', 3, 2, 'Anastasia''s Mate'),
  ('lichess-LQIjP', 3, 2, 'Checkmate in 2'),
  ('lichess-lsWXq', 3, 2, 'Checkmate in 2'),
  ('lichess-LTFZ3', 3, 2, 'Checkmate in 2'),
  ('lichess-lXajP', 3, 2, 'Checkmate in 2'),
  ('lichess-M3dRa', 3, 2, 'Checkmate in 2'),
  ('lichess-m3IIu', 3, 2, 'Checkmate in 2'),
  ('lichess-MDF7c', 3, 2, 'Checkmate in 2'),
  ('lichess-mjHC9', 3, 2, 'Checkmate in 2'),
  ('lichess-MlTtx', 3, 2, 'Checkmate in 2'),
  ('lichess-mmJUa', 3, 2, 'Checkmate in 2'),
  ('lichess-MQifq', 3, 2, 'Back-Rank Mate'),
  ('lichess-MsxlO', 3, 2, 'Back-Rank Mate'),
  ('lichess-mVlb7', 3, 2, 'Checkmate in 2'),
  ('lichess-mWiVb', 3, 2, 'Arabian Mate'),
  ('lichess-N2vqR', 3, 2, 'Checkmate in 2'),
  ('lichess-N7hrV', 3, 2, 'Checkmate in 2'),
  ('lichess-n7l7R', 3, 2, 'Opera Mate'),
  ('lichess-N8Wdc', 3, 2, 'Checkmate in 2'),
  ('lichess-nCI5f', 3, 2, 'Checkmate in 2'),
  ('lichess-NkYN5', 3, 2, 'Checkmate in 2'),
  ('lichess-nNXZV', 3, 2, 'Checkmate in 2'),
  ('lichess-np32n', 3, 2, 'Anastasia''s Mate'),
  ('lichess-NQDWU', 3, 2, 'Checkmate in 2'),
  ('lichess-NSTCl', 3, 2, 'Checkmate in 2'),
  ('lichess-NVeDy', 3, 2, 'Checkmate in 2'),
  ('lichess-Nvf7A', 3, 2, 'Checkmate in 2'),
  ('lichess-NX6HU', 3, 2, 'Checkmate in 2'),
  ('lichess-NXtyV', 3, 2, 'Checkmate in 2'),
  ('lichess-O68cc', 3, 2, 'Checkmate in 2'),
  ('lichess-O7kwJ', 3, 2, 'Vukovic Mate'),
  ('lichess-o7wBc', 3, 2, 'Checkmate in 2'),
  ('lichess-o9z36', 3, 2, 'Double Bishop Mate'),
  ('lichess-ocxKL', 3, 2, 'Checkmate in 2'),
  ('lichess-OD8Mc', 3, 2, 'Checkmate in 2'),
  ('lichess-oiBzG', 3, 2, 'Checkmate in 2'),
  ('lichess-OiFlg', 3, 2, 'Checkmate in 2'),
  ('lichess-OKw79', 3, 2, 'Pillsburys Mate'),
  ('lichess-olf0b', 3, 2, 'Checkmate in 2'),
  ('lichess-OOedR', 3, 2, 'Checkmate in 2'),
  ('lichess-orQwM', 3, 2, 'Checkmate in 2'),
  ('lichess-OSDTv', 3, 2, 'Opera Mate'),
  ('lichess-p6lNy', 3, 2, 'Back-Rank Mate'),
  ('lichess-pbGxf', 3, 2, 'Checkmate in 2'),
  ('lichess-pDACK', 3, 2, 'Checkmate in 2'),
  ('lichess-pdfdA', 3, 2, 'Checkmate in 2'),
  ('lichess-pDmyu', 3, 2, 'Hook Mate'),
  ('lichess-PDszE', 3, 2, 'Checkmate in 2'),
  ('lichess-PK47f', 3, 2, 'Checkmate in 2'),
  ('lichess-PUXEK', 3, 2, 'Anastasia''s Mate'),
  ('lichess-pvXAt', 3, 2, 'Checkmate in 2'),
  ('lichess-Px84z', 3, 2, 'Checkmate in 2'),
  ('lichess-Q1Noh', 3, 2, 'Checkmate in 2'),
  ('lichess-q6Afm', 3, 2, 'Checkmate in 2'),
  ('lichess-qF7D2', 3, 2, 'Checkmate in 2'),
  ('lichess-QGTkq', 3, 2, 'Opera Mate'),
  ('lichess-QhaFp', 3, 2, 'Checkmate in 2'),
  ('lichess-qm1Yo', 3, 2, 'Checkmate in 2'),
  ('lichess-Qm6x8', 3, 2, 'Hook Mate'),
  ('lichess-qNFCd', 3, 2, 'Checkmate in 2'),
  ('lichess-qngwJ', 3, 2, 'Arabian Mate'),
  ('lichess-Qpw3o', 3, 2, 'Checkmate in 2'),
  ('lichess-QVpy9', 3, 2, 'Checkmate in 2'),
  ('lichess-QYosj', 3, 2, 'Opera Mate'),
  ('lichess-R2xrc', 3, 2, 'Hook Mate'),
  ('lichess-RDdOd', 3, 2, 'Checkmate in 2'),
  ('lichess-RE1pd', 3, 2, 'Checkmate in 2'),
  ('lichess-rGKAr', 3, 2, 'Corner Mate'),
  ('lichess-rie7h', 3, 2, 'Checkmate in 2'),
  ('lichess-RJcGU', 3, 2, 'Hook Mate'),
  ('lichess-rkqsa', 3, 2, 'Pillsburys Mate'),
  ('lichess-rTdfy', 3, 2, 'Smothered Mate'),
  ('lichess-RTwBR', 3, 2, 'Checkmate in 2'),
  ('lichess-RvE9h', 3, 2, 'Back-Rank Mate'),
  ('lichess-s1u44', 3, 2, 'Checkmate in 2'),
  ('lichess-sbS1j', 3, 2, 'Checkmate in 2'),
  ('lichess-SCXZ0', 3, 2, 'Checkmate in 2'),
  ('lichess-slP2s', 3, 2, 'Corner Mate'),
  ('lichess-SlxGo', 3, 2, 'Checkmate in 2'),
  ('lichess-SqJ6H', 3, 2, 'Checkmate in 2'),
  ('lichess-SuEso', 3, 2, 'Checkmate in 2'),
  ('lichess-SvanH', 3, 2, 'Checkmate in 2'),
  ('lichess-taDwR', 3, 2, 'Checkmate in 2'),
  ('lichess-TBMHo', 3, 2, 'Checkmate in 2'),
  ('lichess-tbsZp', 3, 2, 'Checkmate in 2'),
  ('lichess-tGITX', 3, 2, 'Checkmate in 2'),
  ('lichess-tKU4h', 3, 2, 'Anastasia''s Mate'),
  ('lichess-To89U', 3, 2, 'Double Bishop Mate'),
  ('lichess-tSbdK', 3, 2, 'Smothered Mate'),
  ('lichess-tt7jT', 3, 2, 'Checkmate in 2'),
  ('lichess-tt8RJ', 3, 2, 'Double Bishop Mate'),
  ('lichess-tvFvo', 3, 2, 'Back-Rank Mate'),
  ('lichess-twnNz', 3, 2, 'Checkmate in 2'),
  ('lichess-tZrN3', 3, 2, 'Checkmate in 2'),
  ('lichess-u9SyQ', 3, 2, 'Checkmate in 2'),
  ('lichess-UD0lQ', 3, 2, 'Swallowstail Mate'),
  ('lichess-udKWy', 3, 2, 'Corner Mate'),
  ('lichess-uF6Kp', 3, 2, 'Arabian Mate'),
  ('lichess-uGrkL', 3, 2, 'Arabian Mate'),
  ('lichess-uKVrO', 3, 2, 'Checkmate in 2'),
  ('lichess-uLaeY', 3, 2, 'Opera Mate'),
  ('lichess-uMTlT', 3, 2, 'Checkmate in 2'),
  ('lichess-UnkRB', 3, 2, 'Checkmate in 2'),
  ('lichess-uqdhd', 3, 2, 'Checkmate in 2'),
  ('lichess-uSV8X', 3, 2, 'Anastasia''s Mate'),
  ('lichess-UTAxl', 3, 2, 'Checkmate in 2'),
  ('lichess-utZl6', 3, 2, 'Checkmate in 2'),
  ('lichess-uZQB7', 3, 2, 'Checkmate in 2'),
  ('lichess-v4pey', 3, 2, 'Double Bishop Mate'),
  ('lichess-v649D', 3, 2, 'Pillsburys Mate'),
  ('lichess-vbYGW', 3, 2, 'Checkmate in 2'),
  ('lichess-vESmA', 3, 2, 'Checkmate in 2'),
  ('lichess-vFj8Z', 3, 2, 'Anastasia''s Mate'),
  ('lichess-vw5LW', 3, 2, 'Checkmate in 2'),
  ('lichess-vxNhB', 3, 2, 'Checkmate in 2'),
  ('lichess-VZLR4', 3, 2, 'Double Bishop Mate'),
  ('lichess-w07lT', 3, 2, 'Checkmate in 2'),
  ('lichess-w1SK3', 3, 2, 'Checkmate in 2'),
  ('lichess-wEIGQ', 3, 2, 'Corner Mate'),
  ('lichess-WJQQq', 3, 2, 'Vukovic Mate'),
  ('lichess-wNdb0', 3, 2, 'Checkmate in 2'),
  ('lichess-wRyCH', 3, 2, 'Anastasia''s Mate'),
  ('lichess-WTm26', 3, 2, 'Checkmate in 2'),
  ('lichess-WvCu3', 3, 2, 'Anastasia''s Mate'),
  ('lichess-Wybpu', 3, 2, 'Kill Box Mate'),
  ('lichess-WZg3e', 3, 2, 'Checkmate in 2'),
  ('lichess-WZprC', 3, 2, 'Checkmate in 2'),
  ('lichess-x3bT1', 3, 2, 'Smothered Mate'),
  ('lichess-X3kOd', 3, 2, 'Pillsburys Mate'),
  ('lichess-X49ae', 3, 2, 'Checkmate in 2'),
  ('lichess-X5xss', 3, 2, 'Checkmate in 2'),
  ('lichess-x6Wpx', 3, 2, 'Checkmate in 2'),
  ('lichess-xBJ3c', 3, 2, 'Checkmate in 2'),
  ('lichess-xJnvv', 3, 2, 'Checkmate in 2'),
  ('lichess-XKjrd', 3, 2, 'Checkmate in 2'),
  ('lichess-xlvoR', 3, 2, 'Checkmate in 2'),
  ('lichess-xmQu4', 3, 2, 'Checkmate in 2'),
  ('lichess-xnCr4', 3, 2, 'Checkmate in 2'),
  ('lichess-XnEoe', 3, 2, 'Checkmate in 2'),
  ('lichess-XPrYD', 3, 2, 'Checkmate in 2'),
  ('lichess-XsJAG', 3, 2, 'Checkmate in 2'),
  ('lichess-xVZZT', 3, 2, 'Checkmate in 2'),
  ('lichess-Y92VZ', 3, 2, 'Anastasia''s Mate'),
  ('lichess-ykl8F', 3, 2, 'Checkmate in 2'),
  ('lichess-ynDE9', 3, 2, 'Checkmate in 2'),
  ('lichess-yQCnv', 3, 2, 'Double Bishop Mate'),
  ('lichess-YSphp', 3, 2, 'Checkmate in 2'),
  ('lichess-yT2Y5', 3, 2, 'Back-Rank Mate'),
  ('lichess-yUcOv', 3, 2, 'Checkmate in 2'),
  ('lichess-yXU5O', 3, 2, 'Checkmate in 2'),
  ('lichess-yY4B1', 3, 2, 'Checkmate in 2'),
  ('lichess-Yz6LX', 3, 2, 'Checkmate in 2'),
  ('lichess-z0yes', 3, 2, 'Back-Rank Mate'),
  ('lichess-zBvJ6', 3, 2, 'Checkmate in 2'),
  ('lichess-ZCkWQ', 3, 2, 'Checkmate in 2'),
  ('lichess-zh3Ds', 3, 2, 'Checkmate in 2'),
  ('lichess-Zkqxo', 3, 2, 'Checkmate in 2'),
  ('lichess-ZN9XP', 3, 2, 'Back-Rank Mate'),
  ('lichess-zOIj6', 3, 2, 'Double Bishop Mate'),
  ('lichess-ZRCSr', 3, 2, 'Double Bishop Mate'),
  ('lichess-ZrN4k', 3, 2, 'Checkmate in 2'),
  ('lichess-ZtWnG', 3, 2, 'Checkmate in 2'),
  ('lichess-zVRAr', 3, 2, 'Checkmate in 2'),
  ('lichess-Zvzh6', 3, 2, 'Checkmate in 2'),
  ('lichess-ZZaUk', 3, 2, 'Checkmate in 2'),
  ('m2-backrank-deflection', 3, 2, 'Back-Rank Mate'),
  ('m2-backrank-ladder-b', 3, 2, 'Back-Rank Mate'),
  ('m2-pawn-rook-corner', 3, 2, 'Pawn & Rook Mate'),
  ('m2-queen-f2-break', 3, 2, 'Queen & Rook Mate'),
  ('m2-queen-king-a', 3, 2, 'Queen & King'),
  ('m2-queen-king-b', 3, 2, 'Queen & King'),
  ('m2-queen-king-mirror', 3, 2, 'Queen & King'),
  ('m2-rook-endgame-hfile', 3, 2, 'King & Rook Mate'),
  ('m2-two-rooks-a', 3, 2, 'Rook Ladder'),
  ('m2-two-rooks-mirror', 3, 2, 'Rook Ladder'),
  ('lichess-503xl', 4, 2, 'Opera Mate'),
  ('lichess-5XArd', 4, 2, 'Checkmate in 2'),
  ('lichess-6ezYm', 4, 2, 'Anastasia''s Mate'),
  ('lichess-6qP9M', 4, 2, 'Checkmate in 2'),
  ('lichess-8urlO', 4, 2, 'Checkmate in 2'),
  ('lichess-c6k2N', 4, 2, 'Opera Mate'),
  ('lichess-CdGKW', 4, 2, 'Double Bishop Mate'),
  ('lichess-cNrLW', 4, 2, 'Anastasia''s Mate'),
  ('lichess-DkF6R', 4, 2, 'Checkmate in 2'),
  ('lichess-dZGkB', 4, 2, 'Checkmate in 2'),
  ('lichess-efo3O', 4, 2, 'Epaulette Mate'),
  ('lichess-GPZCI', 4, 2, 'Anastasia''s Mate'),
  ('lichess-gzled', 4, 2, 'Checkmate in 2'),
  ('lichess-h8jcF', 4, 2, 'Checkmate in 2'),
  ('lichess-hFkKs', 4, 2, 'Checkmate in 2'),
  ('lichess-hiewK', 4, 2, 'Kill Box Mate'),
  ('lichess-i8uTQ', 4, 2, 'Anastasia''s Mate'),
  ('lichess-IBi6U', 4, 2, 'Checkmate in 2'),
  ('lichess-iPbAV', 4, 2, 'Checkmate in 2'),
  ('lichess-j08P9', 4, 2, 'Checkmate in 2'),
  ('lichess-Jzrge', 4, 2, 'Checkmate in 2'),
  ('lichess-kyCWt', 4, 2, 'Epaulette Mate'),
  ('lichess-lAkFk', 4, 2, 'Pillsburys Mate'),
  ('lichess-lpDZl', 4, 2, 'Anastasia''s Mate'),
  ('lichess-MuQKR', 4, 2, 'Checkmate in 2'),
  ('lichess-MZZYn', 4, 2, 'Checkmate in 2'),
  ('lichess-Nn9Tm', 4, 2, 'Anastasia''s Mate'),
  ('lichess-npzVH', 4, 2, 'Checkmate in 2'),
  ('lichess-nUDzp', 4, 2, 'Checkmate in 2'),
  ('lichess-O8ybH', 4, 2, 'Checkmate in 2'),
  ('lichess-oHhnM', 4, 2, 'Checkmate in 2'),
  ('lichess-OIWWb', 4, 2, 'Anastasia''s Mate'),
  ('lichess-oXhuc', 4, 2, 'Arabian Mate'),
  ('lichess-P6T3q', 4, 2, 'Pillsburys Mate'),
  ('lichess-q7vwA', 4, 2, 'Hook Mate'),
  ('lichess-QU7ZY', 4, 2, 'Checkmate in 2'),
  ('lichess-R2M4G', 4, 2, 'Opera Mate'),
  ('lichess-roeBq', 4, 2, 'Checkmate in 2'),
  ('lichess-UBjQW', 4, 2, 'Checkmate in 2'),
  ('lichess-UnTcD', 4, 2, 'Checkmate in 2'),
  ('lichess-vfEAy', 4, 2, 'Dovetail Mate'),
  ('lichess-vjYWH', 4, 2, 'Checkmate in 2'),
  ('lichess-vnZ2i', 4, 2, 'Kill Box Mate'),
  ('lichess-ztGyT', 4, 2, 'Checkmate in 2'),
  ('m2-two-rooks-b', 4, 2, 'Rook Ladder'),
  ('lichess-09IbS', 5, 3, 'Checkmate in 3'),
  ('lichess-0HTZO', 5, 3, 'Checkmate in 3'),
  ('lichess-0jf4v', 5, 3, 'Epaulette Mate'),
  ('lichess-0LOLz', 5, 3, 'Checkmate in 3'),
  ('lichess-0mqJm', 5, 3, 'Checkmate in 3'),
  ('lichess-0wJlX', 5, 3, 'Checkmate in 3'),
  ('lichess-2b4Lt', 5, 3, 'Checkmate in 3'),
  ('lichess-2Blwr', 5, 3, 'Checkmate in 3'),
  ('lichess-2iz2Q', 5, 3, 'Checkmate in 3'),
  ('lichess-2Qhre', 5, 3, 'Checkmate in 3'),
  ('lichess-2rM2P', 5, 3, 'Checkmate in 3'),
  ('lichess-37ezE', 5, 3, 'Checkmate in 3'),
  ('lichess-3gmve', 5, 3, 'Checkmate in 3'),
  ('lichess-3S883', 5, 3, 'Checkmate in 3'),
  ('lichess-4MRnX', 5, 3, 'Opera Mate'),
  ('lichess-4nTM3', 5, 3, 'Checkmate in 3'),
  ('lichess-5wAjc', 5, 3, 'Checkmate in 3'),
  ('lichess-6winl', 5, 3, 'Checkmate in 3'),
  ('lichess-7cEVG', 5, 3, 'Epaulette Mate'),
  ('lichess-7Cur4', 5, 3, 'Back-Rank Mate'),
  ('lichess-7iE6S', 5, 3, 'Checkmate in 3'),
  ('lichess-7KdrM', 5, 3, 'Checkmate in 3'),
  ('lichess-7uef6', 5, 3, 'Checkmate in 3'),
  ('lichess-7xgIR', 5, 3, 'Checkmate in 3'),
  ('lichess-7yzwX', 5, 3, 'Checkmate in 3'),
  ('lichess-80se3', 5, 3, 'Checkmate in 3'),
  ('lichess-8GtkG', 5, 3, 'Checkmate in 3'),
  ('lichess-8tvZ3', 5, 3, 'Checkmate in 3'),
  ('lichess-9d0wI', 5, 3, 'Checkmate in 3'),
  ('lichess-9wdHo', 5, 3, 'Smothered Mate'),
  ('lichess-a2dqo', 5, 3, 'Checkmate in 3'),
  ('lichess-A8ngd', 5, 3, 'Checkmate in 3'),
  ('lichess-apDJC', 5, 3, 'Checkmate in 3'),
  ('lichess-ApGA7', 5, 3, 'Checkmate in 3'),
  ('lichess-aqOcc', 5, 3, 'Hook Mate'),
  ('lichess-audeK', 5, 3, 'Checkmate in 3'),
  ('lichess-avrb7', 5, 3, 'Checkmate in 3'),
  ('lichess-AXka1', 5, 3, 'Checkmate in 3'),
  ('lichess-AzQXm', 5, 3, 'Checkmate in 3'),
  ('lichess-AZxXs', 5, 3, 'Anastasia''s Mate'),
  ('lichess-BbLo7', 5, 3, 'Checkmate in 3'),
  ('lichess-BddQR', 5, 3, 'Back-Rank Mate'),
  ('lichess-bEBUP', 5, 3, 'Checkmate in 3'),
  ('lichess-BhFft', 5, 3, 'Checkmate in 3'),
  ('lichess-bJvkA', 5, 3, 'Checkmate in 3'),
  ('lichess-bNhnW', 5, 3, 'Checkmate in 3'),
  ('lichess-BP2iK', 5, 3, 'Checkmate in 3'),
  ('lichess-bpzwy', 5, 3, 'Checkmate in 3'),
  ('lichess-bt5j8', 5, 3, 'Epaulette Mate'),
  ('lichess-buiUq', 5, 3, 'Checkmate in 3'),
  ('lichess-C7jTX', 5, 3, 'Checkmate in 3'),
  ('lichess-CffjS', 5, 3, 'Checkmate in 3'),
  ('lichess-cjqAD', 5, 3, 'Checkmate in 3'),
  ('lichess-cn3RB', 5, 3, 'Anastasia''s Mate'),
  ('lichess-CSISm', 5, 3, 'Checkmate in 3'),
  ('lichess-cwJPw', 5, 3, 'Checkmate in 3'),
  ('lichess-cyTcM', 5, 3, 'Checkmate in 3'),
  ('lichess-D1pqC', 5, 3, 'Checkmate in 3'),
  ('lichess-D7qT7', 5, 3, 'Epaulette Mate'),
  ('lichess-DHULn', 5, 3, 'Anastasia''s Mate'),
  ('lichess-Di995', 5, 3, 'Checkmate in 3'),
  ('lichess-DlCmM', 5, 3, 'Checkmate in 3'),
  ('lichess-duz9n', 5, 3, 'Checkmate in 3'),
  ('lichess-Dv1rk', 5, 3, 'Checkmate in 3'),
  ('lichess-Dyszy', 5, 3, 'Checkmate in 3'),
  ('lichess-ECAnZ', 5, 3, 'Checkmate in 3'),
  ('lichess-EoJjt', 5, 3, 'Checkmate in 3'),
  ('lichess-evmZJ', 5, 3, 'Checkmate in 3'),
  ('lichess-eYCCS', 5, 3, 'Checkmate in 3'),
  ('lichess-eyjvR', 5, 3, 'Back-Rank Mate'),
  ('lichess-fEqLq', 5, 3, 'Checkmate in 3'),
  ('lichess-fH27A', 5, 3, 'Anastasia''s Mate'),
  ('lichess-fKO5Y', 5, 3, 'Checkmate in 3'),
  ('lichess-fSSOH', 5, 3, 'Pillsburys Mate'),
  ('lichess-Fv9TR', 5, 3, 'Checkmate in 3'),
  ('lichess-G1bAI', 5, 3, 'Checkmate in 3'),
  ('lichess-G4ldC', 5, 3, 'Checkmate in 3'),
  ('lichess-gHk8S', 5, 3, 'Checkmate in 3'),
  ('lichess-GSy2M', 5, 3, 'Checkmate in 3'),
  ('lichess-gVsgH', 5, 3, 'Checkmate in 3'),
  ('lichess-hABVX', 5, 3, 'Checkmate in 3'),
  ('lichess-hhSiV', 5, 3, 'Checkmate in 3'),
  ('lichess-hOzw0', 5, 3, 'Checkmate in 3'),
  ('lichess-I0muB', 5, 3, 'Checkmate in 3'),
  ('lichess-i7pao', 5, 3, 'Checkmate in 3'),
  ('lichess-iAnJY', 5, 3, 'Checkmate in 3'),
  ('lichess-iTuHZ', 5, 3, 'Checkmate in 3'),
  ('lichess-J128B', 5, 3, 'Checkmate in 3'),
  ('lichess-ja3cD', 5, 3, 'Checkmate in 3'),
  ('lichess-jgrSV', 5, 3, 'Checkmate in 3'),
  ('lichess-jOEOJ', 5, 3, 'Checkmate in 3'),
  ('lichess-jTjHR', 5, 3, 'Checkmate in 3'),
  ('lichess-jUEab', 5, 3, 'Checkmate in 3'),
  ('lichess-KfqIP', 5, 3, 'Checkmate in 3'),
  ('lichess-Kl3Tv', 5, 3, 'Checkmate in 3'),
  ('lichess-kROOk', 5, 3, 'Checkmate in 3'),
  ('lichess-Kwe1W', 5, 3, 'Epaulette Mate'),
  ('lichess-L6ahb', 5, 3, 'Checkmate in 3'),
  ('lichess-Ll6FX', 5, 3, 'Checkmate in 3'),
  ('lichess-lM1Ju', 5, 3, 'Anastasia''s Mate'),
  ('lichess-LwKbz', 5, 3, 'Checkmate in 3'),
  ('lichess-LyPOq', 5, 3, 'Checkmate in 3'),
  ('lichess-mhCOY', 5, 3, 'Checkmate in 3'),
  ('lichess-mHF8C', 5, 3, 'Back-Rank Mate'),
  ('lichess-mnUVZ', 5, 3, 'Checkmate in 3'),
  ('lichess-MpcVM', 5, 3, 'Checkmate in 3'),
  ('lichess-MR7hu', 5, 3, 'Hook Mate'),
  ('lichess-muB0w', 5, 3, 'Checkmate in 3'),
  ('lichess-n0sOf', 5, 3, 'Checkmate in 3'),
  ('lichess-N3rOc', 5, 3, 'Checkmate in 3'),
  ('lichess-N61VX', 5, 3, 'Checkmate in 3'),
  ('lichess-Nc2F2', 5, 3, 'Checkmate in 3'),
  ('lichess-NmRHz', 5, 3, 'Checkmate in 3'),
  ('lichess-NRldf', 5, 3, 'Checkmate in 3'),
  ('lichess-nxeG9', 5, 3, 'Checkmate in 3'),
  ('lichess-o1tEh', 5, 3, 'Checkmate in 3'),
  ('lichess-O5aOP', 5, 3, 'Checkmate in 3'),
  ('lichess-oer7b', 5, 3, 'Checkmate in 3'),
  ('lichess-OHUhK', 5, 3, 'Checkmate in 3'),
  ('lichess-OI8jZ', 5, 3, 'Checkmate in 3'),
  ('lichess-OJdJS', 5, 3, 'Checkmate in 3'),
  ('lichess-OVk4Y', 5, 3, 'Checkmate in 3'),
  ('lichess-OYJvw', 5, 3, 'Checkmate in 3'),
  ('lichess-P1vhP', 5, 3, 'Checkmate in 3'),
  ('lichess-p2dmS', 5, 3, 'Checkmate in 3'),
  ('lichess-P5PrX', 5, 3, 'Checkmate in 3'),
  ('lichess-p7H6B', 5, 3, 'Checkmate in 3'),
  ('lichess-PlRrc', 5, 3, 'Checkmate in 3'),
  ('lichess-plvyS', 5, 3, 'Checkmate in 3'),
  ('lichess-pNiQd', 5, 3, 'Checkmate in 3'),
  ('lichess-pYx3W', 5, 3, 'Checkmate in 3'),
  ('lichess-PZOs9', 5, 3, 'Checkmate in 3'),
  ('lichess-QaDE2', 5, 3, 'Checkmate in 3'),
  ('lichess-qBTRn', 5, 3, 'Epaulette Mate'),
  ('lichess-qNr75', 5, 3, 'Checkmate in 3'),
  ('lichess-QNvU2', 5, 3, 'Checkmate in 3'),
  ('lichess-QOdLy', 5, 3, 'Checkmate in 3'),
  ('lichess-qqlbA', 5, 3, 'Checkmate in 3'),
  ('lichess-Qrd02', 5, 3, 'Checkmate in 3'),
  ('lichess-QSQLu', 5, 3, 'Checkmate in 3'),
  ('lichess-qwNA5', 5, 3, 'Checkmate in 3'),
  ('lichess-QyzNY', 5, 3, 'Checkmate in 3'),
  ('lichess-Ra2C1', 5, 3, 'Checkmate in 3'),
  ('lichess-RcJYL', 5, 3, 'Checkmate in 3'),
  ('lichess-rKGwN', 5, 3, 'Checkmate in 3'),
  ('lichess-rnLT5', 5, 3, 'Checkmate in 3'),
  ('lichess-rpRtr', 5, 3, 'Checkmate in 3'),
  ('lichess-Rqeoa', 5, 3, 'Checkmate in 3'),
  ('lichess-RRBqG', 5, 3, 'Checkmate in 3'),
  ('lichess-Rrm9E', 5, 3, 'Checkmate in 3'),
  ('lichess-rY8jn', 5, 3, 'Checkmate in 3'),
  ('lichess-S2gmP', 5, 3, 'Checkmate in 3'),
  ('lichess-s82G4', 5, 3, 'Checkmate in 3'),
  ('lichess-SA3eo', 5, 3, 'Checkmate in 3'),
  ('lichess-Sa8aJ', 5, 3, 'Checkmate in 3'),
  ('lichess-sIRO2', 5, 3, 'Checkmate in 3'),
  ('lichess-SmBL6', 5, 3, 'Checkmate in 3'),
  ('lichess-sqBRb', 5, 3, 'Checkmate in 3'),
  ('lichess-TcM9e', 5, 3, 'Checkmate in 3'),
  ('lichess-tlMoc', 5, 3, 'Arabian Mate'),
  ('lichess-TNcmj', 5, 3, 'Checkmate in 3'),
  ('lichess-trKgc', 5, 3, 'Checkmate in 3'),
  ('lichess-Tuzwy', 5, 3, 'Checkmate in 3'),
  ('lichess-TW6Ia', 5, 3, 'Checkmate in 3'),
  ('lichess-U1hlX', 5, 3, 'Checkmate in 3'),
  ('lichess-UgKOP', 5, 3, 'Checkmate in 3'),
  ('lichess-VBYSX', 5, 3, 'Checkmate in 3'),
  ('lichess-VfV14', 5, 3, 'Checkmate in 3'),
  ('lichess-WiCel', 5, 3, 'Checkmate in 3'),
  ('lichess-wKTcG', 5, 3, 'Checkmate in 3'),
  ('lichess-wNCEG', 5, 3, 'Checkmate in 3'),
  ('lichess-x73fD', 5, 3, 'Checkmate in 3'),
  ('lichess-xaZuO', 5, 3, 'Checkmate in 3'),
  ('lichess-XD87m', 5, 3, 'Checkmate in 3'),
  ('lichess-XY1B9', 5, 3, 'Checkmate in 3'),
  ('lichess-y6WTZ', 5, 3, 'Checkmate in 3'),
  ('lichess-y9VP8', 5, 3, 'Checkmate in 3'),
  ('lichess-Yh1mA', 5, 3, 'Epaulette Mate'),
  ('lichess-yq6Ra', 5, 3, 'Checkmate in 3'),
  ('lichess-zSMy5', 5, 3, 'Checkmate in 3'),
  ('lichess-zvotQ', 5, 3, 'Checkmate in 3'),
  ('lichess-Zyuev', 5, 3, 'Checkmate in 3'),
  ('m3-backrank-infiltration', 5, 3, 'Back-Rank Mate'),
  ('m3-queen-net-a', 5, 3, 'Queen Mating Net'),
  ('m3-queen-net-b', 5, 3, 'Queen Mating Net'),
  ('m3-queen-net-c', 5, 3, 'Queen Mating Net'),
  ('m3-queen-pawn-endgame', 5, 3, 'Queen Mating Net'),
  ('m3-queen-short-side', 5, 3, 'Queen Mating Net'),
  ('m3-rook-box-a', 5, 3, 'Rook Box Mate'),
  ('m3-rook-box-b', 5, 3, 'Rook Box Mate'),
  ('m3-rook-box-c', 5, 3, 'Rook Box Mate'),
  ('m3-rook-ladder-drive', 5, 3, 'Rook Ladder'),
  ('lichess-1NmoC', 6, 3, 'Checkmate in 3'),
  ('lichess-5nrLl', 6, 3, 'Checkmate in 3'),
  ('lichess-9OAoI', 6, 3, 'Checkmate in 3'),
  ('lichess-EHPqe', 6, 3, 'Anastasia''s Mate'),
  ('lichess-iYtIh', 6, 3, 'Checkmate in 3'),
  ('lichess-RRLe5', 6, 3, 'Checkmate in 3'),
  ('lichess-S8SFh', 6, 3, 'Checkmate in 3'),
  ('lichess-wRUsa', 6, 3, 'Checkmate in 3')
on conflict (puzzle_id) do update
  set level = excluded.level, mate_in = excluded.mate_in, theme = excluded.theme;
