-- Fix the trusted-caller authorization in the server-authority migrations.
--
-- WHY THIS EXISTS
--
-- 0037 and 0038 take result reporting and move submission away from the
-- browser by revoking the client's EXECUTE grant, leaving the Next.js route
-- (service role) as the only caller. Both then have to answer one question
-- inside the function: "is this the trusted server, or a browser?"
--
-- They answer it two different ways, and BOTH are wrong.
--
-- 1. 0036 + 0037 do not answer it at all. finish_online_game_by_result keeps
--    `if not v_owns then raise 'Not authorized for this child'`, where v_owns
--    is derived from auth.uid(). The service role has no auth.uid(), so it
--    fails that check. 0037 simultaneously revokes the browser's grant.
--    Applying 0036 and 0037 as written therefore leaves NO caller able to
--    finish a game: the browser is revoked and the server is rejected.
--
--    This is not a reading of the code. It was measured against production,
--    where finish_online_game_by_result is still 0024's definition with the
--    same unconditional check:
--
--      SERVICE ROLE -> 400 {"code":"P0001",
--                           "message":"Not authorized for this child"}
--      row after probe: {"status":"waiting"}      (nothing written)
--
--    Every online game would hang in `active` and no rating would ever
--    settle. 0036 and 0037 MUST NOT be applied without this migration.
--
-- 2. 0038 does answer it, with `if not v_owns and auth.uid() is not null`.
--    The premise is "no auth.uid() means service role". That is false: the
--    anon key's JWT carries {iss, ref, role, iat, exp} and NO `sub` claim, so
--    auth.uid() is NULL for anonymous callers too. Verified directly against
--    this project's anon key. The rule therefore reads "anyone the database
--    cannot identify is trusted", which is the opposite of what is wanted.
--
--    Today it is not exploitable, because 0038's own `revoke ... from public`
--    removes the default PUBLIC grant that anon reaches the function through
--    (there is no explicit `grant ... to anon` anywhere). The two halves
--    cancel out. But the safety then rests entirely on a grant, and 0038's
--    own documented rollback line —
--      grant execute on function public.submit_online_move(...) to authenticated;
--    — restores access to a function whose ownership check has been weakened.
--    An emergency rollback would silently become a privilege escalation.
--
-- THE FIX
--
-- Stop trying to recognise the trusted caller from inside the function.
-- Postgres already has an unspoofable mechanism for exactly this: GRANT.
--
--   * Server-only entry points (`*_as_server`) carry no ownership check at
--     all, because there is no identity to check — they are reachable only by
--     `service_role`, and the route has already authenticated the user and
--     verified participation before calling. Authorization is the grant.
--   * The browser-facing originals get their UNCONDITIONAL ownership check
--     back, and are revoked from every client role. If a grant is ever
--     restored by accident or by an emergency rollback, the function is still
--     safe on its own.
--
-- No claims parsing, no auth.uid() heuristics, no way for an anonymous caller
-- to be mistaken for the server.
--
-- APPLICATION CHANGE REQUIRED (ships with this migration):
--   app/api/online/[gameId]/move/route.ts      -> submit_online_move_as_server
--   app/api/online/[gameId]/complete/route.ts  -> finish_online_game_by_result_as_server
-- Only the RPC name changes; the arguments are identical.
--
-- ORDERING: apply AFTER 0038. Additive and idempotent — safe to run more than
-- once, and correct whether or not 0036/0037/0038 have already been applied.

-- ---------------------------------------------------------------------------
-- 1. Server-only move submission
-- ---------------------------------------------------------------------------
-- Same body as 0038's submit_online_move, minus the ownership guess. Keeps
-- everything that is genuinely decidable in SQL: participation, whose turn it
-- is, the clock arithmetic on server time, the flag-fall — and 0038's fix for
-- untimed games, which previously returned BEFORE the turn check and so had no
-- turn enforcement at all.
--
-- p_fen / p_san are generated by lib/online/moveValidation.ts from a chess.js
-- replay of the authoritative move list. They are never client values.

create or replace function public.submit_online_move_as_server(
  p_game_id uuid,
  p_child_id uuid,
  p_fen text,
  p_san text
)
returns table(white_time_ms bigint, black_time_ms bigint, status text, winner text)
language plpgsql
security definer set search_path = public
as $$
declare
  g record;
  v_is_host boolean;
  v_mover_color text;
  v_new_turn text;
  v_now timestamptz := clock_timestamp();
  v_elapsed_ms bigint;
  v_white_ms bigint;
  v_black_ms bigint;
begin
  select * into g from online_games where id = p_game_id for update;
  if g.id is null then
    raise exception 'Game not found';
  end if;

  -- No ownership check: this function is granted to service_role only, and the
  -- caller (app/api/online/[gameId]/move) has already resolved the signed-in
  -- user's active child. Participation IS still checked, because it is a
  -- property of the row rather than of the caller's identity.
  v_is_host := (g.host_child_id = p_child_id);
  if not v_is_host and g.guest_child_id is distinct from p_child_id then
    raise exception 'Not a participant in this game';
  end if;

  if g.status <> 'active' then
    raise exception 'Game is not active';
  end if;

  v_mover_color := case
    when v_is_host then g.host_color
    else (case when g.host_color = 'w' then 'b' else 'w' end)
  end;

  -- Untimed games. The pre-0038 definition wrote the move and RETURNED before
  -- the turn check below, so either player could move at any time, including
  -- the opponent's pieces. current_turn is null on rows created before clocks
  -- existed; that is treated as "no constraint recorded" rather than a
  -- rejection, so legacy games keep working.
  if g.time_control is null then
    if g.current_turn is not null and g.current_turn is distinct from v_mover_color then
      raise exception 'Not your turn';
    end if;
    update online_games
    set fen = p_fen,
        moves = array_append(moves, p_san),
        current_turn = case when v_mover_color = 'w' then 'b' else 'w' end
    where id = p_game_id;
    return query select null::bigint, null::bigint, g.status, g.winner;
    return;
  end if;

  if g.current_turn is distinct from v_mover_color then
    raise exception 'Not your turn';
  end if;

  v_elapsed_ms := greatest(0, (extract(epoch from (v_now - g.last_move_at)) * 1000))::bigint;
  v_white_ms := g.white_time_ms;
  v_black_ms := g.black_time_ms;

  if v_mover_color = 'w' then
    v_white_ms := g.white_time_ms - v_elapsed_ms;
  else
    v_black_ms := g.black_time_ms - v_elapsed_ms;
  end if;

  -- The clock fell during this move: the move does not land, the flag does.
  if (v_mover_color = 'w' and v_white_ms <= 0) or (v_mover_color = 'b' and v_black_ms <= 0) then
    update online_games
    set status = 'finished',
        winner = case when v_mover_color = 'w' then 'b' else 'w' end,
        white_time_ms = greatest(0, v_white_ms),
        black_time_ms = greatest(0, v_black_ms)
    where id = p_game_id;
    return query select greatest(0, v_white_ms), greatest(0, v_black_ms),
      'finished'::text, (case when v_mover_color = 'w' then 'b' else 'w' end)::text;
    return;
  end if;

  if v_mover_color = 'w' then
    v_white_ms := v_white_ms + g.increment_ms;
  else
    v_black_ms := v_black_ms + g.increment_ms;
  end if;

  v_new_turn := case when v_mover_color = 'w' then 'b' else 'w' end;

  update online_games
  set fen = p_fen,
      moves = array_append(moves, p_san),
      current_turn = v_new_turn,
      white_time_ms = v_white_ms,
      black_time_ms = v_black_ms,
      last_move_at = v_now
  where id = p_game_id;

  return query select v_white_ms, v_black_ms, 'active'::text, null::text;
end;
$$;

-- ---------------------------------------------------------------------------
-- 2. Server-only result reporting
-- ---------------------------------------------------------------------------
-- The winner is derived by app/api/online/[gameId]/complete, which replays the
-- stored moves with chess.js. 0036's minimum-plies guard is kept as defence in
-- depth: it only ever rejects a player claiming a win for THEMSELVES before a
-- checkmate is arithmetically possible, so it cannot reject a resignation, a
-- draw, or a timeout awarded against the flagged player.

create or replace function public.finish_online_game_by_result_as_server(
  p_game_id uuid,
  p_child_id uuid,
  p_winner text
)
returns void
language plpgsql
security definer set search_path = public
as $$
declare
  g record;
  v_my_color text;
  -- 1. f3 e5 2. g4 Qh4# — the shortest mate there is.
  v_min_plies_for_mate constant int := 4;
begin
  if p_winner not in ('w', 'b', 'draw') then
    raise exception 'Invalid winner';
  end if;

  select * into g from online_games where id = p_game_id for update;
  if g.id is null then
    raise exception 'Game not found';
  end if;

  if g.host_child_id <> p_child_id and g.guest_child_id is distinct from p_child_id then
    raise exception 'Not a participant in this game';
  end if;

  -- Idempotent no-op rather than an error: both clients legitimately report a
  -- result at almost the same instant, and the sweeper in a later phase must be
  -- safe to run repeatedly. Also blocks post-finish result tampering.
  if g.status <> 'active' then
    return;
  end if;

  if g.match_type = 'random' and p_winner in ('w', 'b') then
    v_my_color := case
      when p_child_id = g.host_child_id then g.host_color
      else case when g.host_color = 'w' then 'b' else 'w' end
    end;

    if p_winner = v_my_color
       and coalesce(array_length(g.moves, 1), 0) < v_min_plies_for_mate then
      raise exception 'Cannot claim a win before a checkmate is possible';
    end if;
  end if;

  update online_games set status = 'finished', winner = p_winner where id = p_game_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- 3. Re-harden the browser-facing originals
-- ---------------------------------------------------------------------------
-- Undo 0038's `and auth.uid() is not null`. With the server on its own entry
-- point this function has no legitimate service-role caller left, so the check
-- can be unconditional again — which is what makes it safe to hold a grant, and
-- therefore safe for someone to run 0038's rollback line in an emergency.
--
-- Written as a full definition rather than a patch so that it lands correctly
-- whether the live function is 0021's or 0038's.

create or replace function public.submit_online_move(
  p_game_id uuid,
  p_child_id uuid,
  p_fen text,
  p_san text
)
returns table(white_time_ms bigint, black_time_ms bigint, status text, winner text)
language plpgsql
security definer set search_path = public
as $$
declare
  v_owns boolean;
begin
  select exists (
    select 1 from children c join parents p on p.id = c.parent_id
    where c.id = p_child_id and p.auth_user_id = auth.uid()
  ) into v_owns;

  -- Unconditional. An unidentifiable caller is NOT a trusted caller: the anon
  -- role also has no auth.uid(). The trusted server uses
  -- submit_online_move_as_server, which is gated by GRANT instead.
  if not v_owns then
    raise exception 'Not authorized for this child';
  end if;

  -- A browser may no longer write the board even if it somehow holds the
  -- grant: it cannot generate a trustworthy FEN/SAN, which is the whole point
  -- of routing moves through app/api/online/[gameId]/move.
  raise exception 'Direct move submission is disabled; use /api/online/<id>/move';
end;
$$;

-- ---------------------------------------------------------------------------
-- 4. Grants — the actual authorization boundary
-- ---------------------------------------------------------------------------
-- Postgres creates functions with EXECUTE granted to PUBLIC, which is how the
-- anon role reaches them at all. Revoke first, then grant narrowly.

revoke execute on function public.submit_online_move_as_server(uuid, uuid, text, text) from public;
revoke execute on function public.submit_online_move_as_server(uuid, uuid, text, text) from anon;
revoke execute on function public.submit_online_move_as_server(uuid, uuid, text, text) from authenticated;
grant  execute on function public.submit_online_move_as_server(uuid, uuid, text, text) to service_role;

revoke execute on function public.finish_online_game_by_result_as_server(uuid, uuid, text) from public;
revoke execute on function public.finish_online_game_by_result_as_server(uuid, uuid, text) from anon;
revoke execute on function public.finish_online_game_by_result_as_server(uuid, uuid, text) from authenticated;
grant  execute on function public.finish_online_game_by_result_as_server(uuid, uuid, text) to service_role;

-- The originals stay revoked from every client role (0037/0038 did this; state
-- it again so this migration is correct on its own).
revoke execute on function public.submit_online_move(uuid, uuid, text, text) from public;
revoke execute on function public.submit_online_move(uuid, uuid, text, text) from anon;
revoke execute on function public.submit_online_move(uuid, uuid, text, text) from authenticated;

revoke execute on function public.finish_online_game_by_result(uuid, uuid, text) from public;
revoke execute on function public.finish_online_game_by_result(uuid, uuid, text) from anon;
revoke execute on function public.finish_online_game_by_result(uuid, uuid, text) from authenticated;

-- claim_timeout deliberately KEEPS its grant. It is already authoritative — it
-- decides expiry from clock_timestamp() and last_move_at, and a premature call
-- returns the unchanged state — so a browser calling it cannot influence the
-- outcome. Phase 2's server-side sweeper will call the same logic; it does not
-- need this privilege removed.

-- ---------------------------------------------------------------------------
-- 5. VERIFICATION (read-only — run after applying, expect the stated results)
-- ---------------------------------------------------------------------------
-- (a) No client role may execute any of the four authority functions, and
--     service_role may execute both server entry points.
--     Expect: exactly two rows, both grantee=service_role, both *_as_server.
--
-- select p.proname, r.rolname as grantee
-- from pg_proc p
-- join pg_namespace n on n.oid = p.pronamespace
-- cross join lateral aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) a
-- join pg_roles r on r.oid = a.grantee
-- where n.nspname = 'public'
--   and p.proname in ('submit_online_move', 'submit_online_move_as_server',
--                     'finish_online_game_by_result',
--                     'finish_online_game_by_result_as_server')
--   and a.privilege_type = 'EXECUTE'
--   and r.rolname in ('anon', 'authenticated', 'service_role', 'public')
-- order by p.proname, r.rolname;
--
-- (b) PUBLIC must not hold EXECUTE on any of them.
--     Expect: 0 rows.
--
-- select p.proname
-- from pg_proc p
-- join pg_namespace n on n.oid = p.pronamespace
-- cross join lateral aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) a
-- where n.nspname = 'public'
--   and p.proname in ('submit_online_move', 'submit_online_move_as_server',
--                     'finish_online_game_by_result',
--                     'finish_online_game_by_result_as_server')
--   and a.privilege_type = 'EXECUTE'
--   and a.grantee = 0;   -- 0 is PUBLIC
--
-- (c) No live game was disturbed by applying this migration.
--     Expect: the same counts as before you ran it.
--
-- select status, count(*) from public.online_games group by status order by status;

-- ---------------------------------------------------------------------------
-- ROLLBACK
-- ---------------------------------------------------------------------------
-- Safe, because the originals now hard-fail on their own rather than relying on
-- a grant. To restore the pre-0037/0038 browser path you must ALSO restore the
-- pre-0038 function bodies from 0021/0024 — re-granting alone will not do it,
-- which is the point:
--
--   -- 1. re-run the body from 0021 (submit_online_move) and 0024 or 0036
--   --    (finish_online_game_by_result), then:
--   grant execute on function public.submit_online_move(uuid, uuid, text, text) to authenticated;
--   grant execute on function public.finish_online_game_by_result(uuid, uuid, text) to authenticated;
--   -- 2. revert the two API routes to the un-suffixed RPC names.
